### ISSUE TITLE
Format om.next defui macro

### ISSUE THREAD

**Issue by mitchelkuijpers** [kkinnear/zprint#10]
```
(defui AnimalsList
  static om/IQueryParams
  (params [this]
    {:start 0 :end 10})
  static om/IQuery
  (query [this]
    '[:app/title (:animals/list {:start ?start :end ?end})])
  Object
  (render [this]
    (let [{:keys [app/title animals/list]} (om/props this)]
      (dom/div nil
        (dom/h2 nil title)
        (apply dom/ul nil
          (map
            (fn [[i name]]
              (dom/li nil (str i ". " name)))
            list))))))
```

Do you have any idea how to format such a macro?

**Comment by kkinnear** [comment]
I don't have access to my code right this instant, but I think if you define defui as :arg1-extend, it should do what you want. Failing that you might try :extend. 

You want to look at the  readme on how to define a function type. Let me know if that isn't clear. 
 
I'll try this myself later today.

**Comment by mitchelkuijpers** [comment]
I tried them both before making this issue.  But it failed on the `static om/IQuery` case it would add line endings between them

**Comment by kkinnear** [comment]
Oh, of course. Missed that since I couldn't try it myself. Interesting problem, since you can have two protocols without functions between them, at least for either proxy or reify, and probably for other stuff. So I can't just say "two non-collections should be on the same line" or something. 

I'm not an Om user, or really a clojurescript user much at all. Is this common?  That is to say, should I come up with an :extend variant that puts two non-collections on the same line?  

Or is static the only thing that can come here?  If so, I might be able to special case that and just put static on the same line. 

Thanks for bringing this up!

**Comment by mitchelkuijpers** [comment]
For Om static is the only possible thing, they are pretty much the only
ones doing this (as far as I know)

BTW loving this library feels like having elm-format in clojure/script ^^

Op ma 12 dec. 2016 21:49 schreef Kim Kinnear <notifications@github.com>:

**Comment by kkinnear** [comment]
I'll see about implementing something that will place these on the same line.  This is in line behind some other enhancements, but I will get to it!   I'll make it the default for `defui`.
Thanks for pointing out the issue!

[Thanks as well for the positive feedback about the library.  It really makes the effort more worthwhile when people who appreciate it actually tell me!]

**Comment by kkinnear** [comment]
I have added a capability to do this in zprint 0.2.14 and lein-zprint 0.1.14.  The single elements that can come before the protocol/interface/Object are called "modifiers".  Since "static" is unlikely to be a protocol/interface/Object on its own, I have made it a "modifier" for everyone.   You can now configure any number of modifiers, but "static" is the only one currently configured.

If you just use the defaults, you will get this:
```clojure
(defui AnimalsList
  static om/IQueryParams (params [this] {:start 0, :end 10})
  static om/IQuery (query [this]
                     '[:app/title (:animals/list {:start ?start, :end ?end})])
  Object (render [this]
           (let [{:keys [app/title animals/list]} (om/props this)]
             (dom/div nil
                      (dom/h2 nil title)
                      (apply dom/ul
                        nil
                        (map (fn [[i name]] (dom/li nil (str i ". " name)))
                          list))))))
```
You can make it a bit more like what you have above by adding `{:extend {:flow? true :indent 0}}`:

```clojure
(defui AnimalsList
  static om/IQueryParams 
  (params [this] {:start 0, :end 10})
  static om/IQuery
  (query [this] '[:app/title (:animals/list {:start ?start, :end ?end})])
  Object
  (render [this]
    (let [{:keys [app/title animals/list]} (om/props this)]
      (dom/div nil
               (dom/h2 nil title)
               (apply dom/ul
                 nil
                 (map (fn [[i name]] (dom/li nil (str i ". " name))) list))))))
```
You might find that adding `:nl-separator? true` will get you something better.  To make this easier, there is a style which has `{:extend {:flow? true :indent 0 :nl-separator? true}}` called `:extend-nl`, which you can use thus:

If you use `{:style :extend-nl}` you will get this:
```clojure
(defui AnimalsList
  static om/IQueryParams 
  (params [this] {:start 0, :end 10})
  
  static om/IQuery
  (query [this] '[:app/title (:animals/list {:start ?start, :end ?end})])
  
  Object
  (render [this]    
    (let [{:keys [app/title animals/list]} (om/props this)]
      (dom/div nil
               (dom/h2 nil title)
               (apply dom/ul
                 nil
                 (map (fn [[i name]] (dom/li nil (str i ". " name))) list))))))
```
Hopefully, one of these will be what you were looking for.

Note that you could put `{:style :extend-nl}` (or whatever) in your ~/.zprintrc file, if you want to globally change the way some of these things are formatted.  You can also put:
```clojure
;!zprint {:style :extend-nl}
```
at the start of a file, to change zprint for just that file.

Or even put the following as a comment before the `defui` macro in your source file:
```clojure
;!zprint {:format :next :style :extend-nl}
```
which will just set the style for the next top-level form in a a file.

**Comment by mitchelkuijpers** [comment]
Wow this is absolutely perfect, I tested it out and it does exactly what I want. Thank you so much. I think we can close this one ^^

**Comment by kkinnear** [comment]
Just getting around to closing this, it all seems to have continued to work.
