### ISSUE TITLE
Wrong tag format for defrecord

### ISSUE THREAD

**Issue by glebdom4** [kkinnear/zprint#105]
Wrong tag format for defrecord.
Example:
1) (spit file-name (prn-str component))
     result: #metagraph.graph.Vertex{:name "v1", :attrs {:a 1, :b "aaa"}}
     (read-string (slurp  "v1-2019-05-07T03:06:07-SNAPSHOT.edn"))
     result: object created

2) (spit file-name (zp/zprint-str component {:record {:hang? nil}})
     result: #metagraph.graph/Vertex {:attrs {:a 1, :b "aaa"}, :name "v1"}
     (read-string (slurp  "v1-2019-05-07T03:09:07-SNAPSHOT.edn"))
     result: Execution error at metagraph.core/deserialize (core.clj:67).
                No reader function for tag metagraph.graph/Vertex

**Comment by kkinnear** [comment]
I don't doubt that there is a bug here, and I'd love to fix it prior to the next release (which is coming up pretty soon, as the list of bugs to fix has grown quite large enough).  I'm having trouble reproducing this problem -- which is not to say that it works, but rather that I don't know enough to convince your Metagraph library to give me something that fails so I can actually debug this issue.  While I'm sure that eventually I will figure out Metagraph enough to generate a Vertex that will fail, it would help me out a lot if you could give me some code that would generate a `component` (presumably a Vertex?) that causes this problem.  Then I could work on fixing zprint instead of trying to recreate the problem.  Thanks!

**Comment by glebdom4** [comment]
I am very sorry that there is no documentation in the repository of my
library.  Tomorrow I will send you an example of how to create a vertex of
the metagraph to reproduce the problem.  In addition, I'd like to try to
fix this bug myself this weekend.

**Comment by kkinnear** [comment]
Based on email that you sent me, I have reproduced this problem.  I see no reason to persist in the output format: `#metagraph.graph/Vertex {...}`, when `#metagraph.graph.Vertex {...}` will actually be in a format to be read back in with the reader.  I will change zprint to put a "." instead of a "/" prior to the record name.

**Comment by kkinnear** [comment]
This is fixed in version 0.4.16.
