### ISSUE TITLE
Add a empty line between top level forms

### ISSUE THREAD

**Issue by mynomoto** [kkinnear/zprint#11]
As a config option

**Comment by mynomoto** [comment]
So that
```clojure
(defn xxx []
  body)
(defn yyy []
  body)
```
becomes
```clojure
(defn xxx []
  body)

(defn yyy []
  body)
```

**Comment by kkinnear** [comment]
I assume that you want this in a file formatted by `lein-zprint` or `boot-fmt`.  At present, the formatter that processes entire files doesn't change the whitespace at the "top level" of the file, it only changes the whitespace inside of top level forms (e.g., `defn` forms).  The reason for this is that I don't know of any approach that I could adopt that would satisfy more than a small number of folks.  Personally, I don't want a program messing with the top level of my files, and I don't think most other people do either.

In the event that you want this behavior when formatting forms in a string, using `:parse-string-all?`, you can get whatever spacing you want using the `:interpose` key.  I doubt this is what you were asking for, though.

I have no current plans to change the white space at the top level of files.  You are welcome to try to persuade me otherwise, and I will certainly listen, and it is possible you will convince me.  But it is going to take a bit of convincing.

**Comment by kkinnear** [comment]
Thanks for the interest, but I don't plan to make this change.
