### ISSUE TITLE
Add option to format pairs to add a blank line between pairs when the pairs don't fit in a single line

### ISSUE THREAD

**Issue by mynomoto** [kkinnear/zprint#12]
So that
```clojure
{:a-big-key :a-really-long-value...
 :c :d}
```
becomes
```clojure
{:a-big-key
 :a-really-long-value...

 :c :d}
```

**Comment by kkinnear** [comment]
Sure, I'll add this.  It is backed up behind some other things people have requested, so it may be a bit before it is completed, but it makes sense.  It isn't my favorite approach personally, but I have seen it used by a number of people.

**Comment by kkinnear** [comment]
This is implemented in zprint 0.2.11, lein-zprint 0.1.11.  To get it to work, you would use `:nl-separator? true`, like this:

```clojure
(czprint {:a-big-key :a-really-long-value-and-even-longer :c :d} 40)

{:a-big-key
   :a-really-long-value-and-even-longer,
 :c :d}

(czprint {:a-big-key :a-really-long-value-and-even-longer :c :d} 40 {:map {:nl-separator? true :indent 0}})

{:a-big-key
 :a-really-long-value-and-even-longer,
 
 :c :d}

; You might find that this worked better with some of the maps that you end up with, though
; it doesn't affect this example

(czprint {:a-big-key :a-really-long-value-and-even-longer :c :d} 40 {:map {:nl-separator? true :indent 0 :hang? false}})

{:a-big-key
 :a-really-long-value-and-even-longer,
 
 :c :d}
```

Let me know if this is not what you were expecting, we I'll see what we can do about it.

**Comment by mynomoto** [comment]
This is exactly what I wanted, thanks!

**Comment by kkinnear** [comment]
So, in part because of the capabilities unlocked because I implemented this new-line thing, I've added the ability to set multiple styles in one configuration (with a vector of style names instead of a single style name).  I am making up some more styles, and I would like to make one called `:map-nl`, to do what you asked for so that people don't have to set two or three things in the `{:map ...}` configuration element to get what you want.  I'm unclear if it should be `{:map {:hang? false :nl-separator? true :indent 0}]` or `{:map (:hang? true :nl-separator? true :indent 0}}`. 

Here is an example of the difference of having `:hang?` `true` or `false`:

```clojure
(czprint sort-demo {:map {:nl-separator? true :indent 0}})

; :hang? true

[{:code       "58601",
  :connection "2795",
  :detail     {:alternate "64:c1:2f:34",
               :ident     "64:c1:2f:34",
               :interface "3.13.168.35",
               :string    "datacenter"},
  
  :direction  :received,
  :reference  14873,
  :time       1425704001,
  :type       "get"}
 {:code       "0xe4e9",
  :connection "X13404",
  :detail     {:code  "0xe4e9",
               :ident "64:c1:2f:34",
               :ip4   "3.13.168.151",
               :time  "30m"},
  
  :direction  :transmitted,
  :reference  14133,
  :time       1425704001,
  :type       "post"}
 {:code       "58601",
  :connection "X13404",
  :direction  :transmitted,
  :reference  14227,
  :time       1425704001,
  :type       "post"}
 {:code       "0x1344a676",
  :connection "2796",
  :detail     {:code "0x1344a676", :ident "50:56:a5:1d:61", :ip4 "3.13.171.81"},
  :direction  :received,
  :reference  14133,
  :time       1425704003,
  :type       "error"}
 {:code       "323266166",
  :connection "2796",
  :detail     {:alternate "01:50:56:a5:1d:61",
               :ident     "50:56:a5:1d:61",
               :interface "3.13.168.35",
               :string    "datacenter"},
  
  :direction  :transmitted,
  :reference  14873,
  :time       1425704003,
  :type       "error"}]



 (czprint sort-demo {:map {:nl-separator? true :indent 0 :hang? false}})

; :hang? false

[{:code "58601",
  :connection "2795",
  :detail
  {:alternate "64:c1:2f:34",
   :ident     "64:c1:2f:34",
   :interface "3.13.168.35",
   :string    "datacenter"},
  
  :direction :received,
  :reference 14873,
  :time 1425704001,
  :type "get"}
 {:code "0xe4e9",
  :connection "X13404",
  :detail
  {:code "0xe4e9", :ident "64:c1:2f:34", :ip4 "3.13.168.151", :time "30m"},
  
  :direction :transmitted,
  :reference 14133,
  :time 1425704001,
  :type "post"}
 {:code       "58601",
  :connection "X13404",
  :direction  :transmitted,
  :reference  14227,
  :time       1425704001,
  :type       "post"}
 {:code       "0x1344a676",
  :connection "2796",
  :detail     {:code "0x1344a676", :ident "50:56:a5:1d:61", :ip4 "3.13.171.81"},
  :direction  :received,
  :reference  14133,
  :time       1425704003,
  :type       "error"}
 {:code "323266166",
  :connection "2796",
  :detail
  {:alternate "01:50:56:a5:1d:61",
   :ident     "50:56:a5:1d:61",
   :interface "3.13.168.35",
   :string    "datacenter"},
  
  :direction :transmitted,
  :reference 14873,
  :time 1425704003,
  :type "error"}]
```
I would presume that, since you like maps formatted with the blank line, that you have a preference between these two approaches.  Thanks, by the way, for asking for the blank line in maps -- it has also made the formatting of `:extend` items much more flexible (since there are several ways people format `:extend` stuff). Thanks also for your feedback on how to define `:map-nl`!

**Comment by mynomoto** [comment]
In the `:hang? false` example the formatting seems inconsistent. Looks like the `:justify` option is being affected by the change. In any case, I'm in favor of `:hang? true` as the default.

**Comment by kkinnear** [comment]
So, I found a serious bug in :nl-separator?, and I've been thinking about it a lot whlie fixing the bug.  I'd like your opinion on something.  Two approaches to when to put in a blank line when specifiying `:nl-separator? true`:


```clojure
; Example A
{:ajfkdkfdj :bjlfkdsfjsdl,
 :cjslkfsdjl :dklsdfjsdsjsldf,
 :const1
 ["stuff" "that" "is" "really"
  "long" "and" "should"
  "trigger" "nl-separator?"],

 :const2 "bother"}

; Example B
{:ajfkdkfdj :bjlfkdsfjsdl,
 :cjslkfsdjl :dklsdfjsdsjsldf,
 :const1 ["stuff" "that" "is" "really"
          "long" "and" "should"
          "trigger" "nl-separator?"],

 :const2 "bother"}

; Example C
{:ajfkdkfdj :bjlfkdsfjsdl,
 :cjslkfsdjl :dklsdfjsdsjsldf,
 :const1 ["stuff" "that" "is" "really"
          "long" "and" "should"
          "trigger" "nl-separator?"],
 :const2 "bother"}
```

Presently, the code puts in a blank line like in example A and B when you say `:nl-separator? true`.  I'm thinking that maybe there should not be a blank line when the right hand part of a pair formats in a "hang",  which would make example B end up looking like example C.  My thinking is that you aren't really confused about `:const2` in the example B/C case, since the `["stuff"...]` didn't end up back at the left.

Do you have a preference here?  I'm going to allow both, but I'm wondering which you think should be the default?

Thanks!

**Comment by mynomoto** [comment]
I think C is more common than B and my preference also. Also thanks again for this amazing library :100:
