### ISSUE TITLE
Honor {:search-config? true} on command-line

### ISSUE THREAD

**Issue by agriffis** [kkinnear/zprint#120]
I've started working on a zprint formatter for Google's vim-codefmt here: https://github.com/google/vim-codefmt/pull/130

The trouble is that it seems like `zprint '{:search-config? true}'` doesn't work. It only works if this is set in `~/.zprintrc`. Easy to see with strace:

```
✸ pwd
/home/aron/foo

✸ touch .zprintrc

✸ strace zprint '{:search-config? true}' </dev/null 2>&1 | grep zprintrc
lstat("/home/aron/.zprintrc", 0x7ffdf9788c70) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/aron/.zprintrc", O_RDONLY) = -1 ENOENT (No such file or directory)

✸ echo '{:search-config? true}' > ~/.zprintrc

✸ strace zprint </dev/null 2>&1 | grep zprintrc
lstat("/home/aron/.zprintrc", {st_mode=S_IFREG|0664, st_size=23, ...}) = 0
openat(AT_FDCWD, "/home/aron/.zprintrc", O_RDONLY) = 3
lstat("/home/aron/foo/.zprintrc", {st_mode=S_IFREG|0664, st_size=22, ...}) = 0
openat(AT_FDCWD, "./.zprintrc", O_RDONLY) = 4
```

Is this intentional? I'd like to be able to support `.zprintrc` in project directories without needing a personal `~/.zprintrc` -- maybe there's another way to do it?

**Comment by kkinnear** [comment]
I'm delighted you are working on this. 

Yes, that was intentional.  From the readme:

> When zprint (or one of the zprint-filters) is called for the first time it will configure itself from all of the information that it has available at that time. It will examine the following information in order to configure itself:
> 
> o The file $HOME/.zprintrc or if that file does not exist, the file $HOME/.zprint.edn for an options map in EDN format.
>
> o If the file found above has :search-config? true, it will look in the current directory for a file .zprintrc and if it doesn't find one, it will look for .zprint.edn. If it doesn't find either of them, it will look in the parent of the current directory for the same two files, in the same order. This process will stop when it finds a file or it reaches the root of the file system. If the file it finds is in the home directory (that is, it is the same file found in the first step in this process, above), it will read the file but it will not use the results (because it has already done so).
>
> o If the file found in the home directory has :cwd-zprintrc? set to true, and did not have :search-config? set to true, then it will search the current directory for .zprintrc and .zprint.edn in that order, and use the information from the first file it finds.

This was done because the `:search-config?` capability was added after zprint was first released, and so I didn't want people getting unexpected results.  I suppose I could have changed this with the 0.5.x release, but it is a bit too late for that.

However, I expect that we can work something out that will meet your needs.  Two questions:

1. Do you want the full-on `:search-config?` capability, where zprint will look not only in the current directory but move up the directory tree looking for a .zprintrc (or .zprint.edn) until it finds one?  Or do you only want it to look in the current directory (which is currently available with the `:cwd-zprintrc?` key, though it has the same current limitations).

2. Are you actually expecting to use the filters (uberjar or graalVM binaries), or the library? I can come up with a solution for either, but it might be slightly different, so it would help to know your specific use case.

It is worth knowing that I'm currently integrating a pull request whose function is to also allow zprint to be configured by reading an options map from a URL.  This will typically be triggered by a switch `--url` or `--url-only` given to the uberjar or graalVM binaries.  You will be able to do this for the library as well, but it will be a bit different.

Anyway, we should be able to come up with something that will work.  This will be a nice capabiliity to have!

**Comment by agriffis** [comment]
Regarding this:

> When zprint (or one of the zprint-filters) is called for the first time it will configure itself from all of the information that it has available at that time.

I imagined this would include the configuration given on the command-line. I'm not completely sure this part of my original report was understood. The command-line I'm using is this:

```
zprint '{search-config? true}'
```

Regarding your questions:

> 1. Do you want the full-on `:search-config?` capability...?

I was hoping that whichever capability was specified on the command-line would take effect.

> 2. Are you actually expecting to use the filters (uberjar or graalVM binaries), or the library?

Right now the plugin executes an external command which defaults to `zprint` and I expect is probably the GraalVM binary, at least that's what I'm using. In the future we could also use a fireplace.vim REPL session for the library, but for now I'd be happy to get the external filter working.

**Comment by kkinnear** [comment]
Let me try to explain why, currently, adding `{:search-config? true}` on the command line doesn't get you what you expect.

The way that configuration currently works is that it _combines_ configuration from, potentially, several different places.  It does this combination from "least specific" to "most specific" (in theory), with the intent to let the later option maps override information in the earlier option maps. The earliest option map is `$HOME/.zprintrc`, the next option map is the single one that comes from `{:search-config? true}` or `{:cwd-zprintrc? true}` (if any), and the last option map is the one specified on the command line.  Thus, if the command line option map specifies something that was also specified in a previous option map, the command line option map "wins".

`{:search-config? true}` isn't the default (for reasons that I explained above), and specifying it in the command line option map is not rejected, but it is too late to make any difference -- since by the time the command line option map is examined, the other option maps have already been merged (or not, in this case).  There is no way -- at present -- for the command line option map to affect __which__ option maps are used _prior_ to the command line option map.

What I am discovering is that the option map has conflated two things: format configuration, and zprint operation configuration (e.g., `:search-config?`, `:parallel?`, etc.).

My thinking is that I could have the code that merges option maps examine the command-line option map and, if it specified either `{:search-config? true}` or `{:cwd-zprintrc? true}`, then these option maps would be included in the configuration.    I believe that this would give you what you want.  Do you agree?

**Comment by agriffis** [comment]
Thanks, that explanation is helpful and makes sense!

I agree that approach should work for me. And since it's pure EDN instead of executable code with potential side effects, there's no harm in peeking early then merging later!

**Comment by kkinnear** [comment]
That's ... a very good point.  About executable code. I hadn't actually considered that, so thanks for bringing it up. 

I'll try to add this to the next release.  I hope that I can get something out before the conj next week.  It will be a bit of a challenge, but I'm hopeful.

**Comment by kkinnear** [comment]
Wow, I thought I'd get this out before the conj.  Bit optimistic.  Anyway, it now works in 0.5.4.  If you put `:cwd-zprintrc?` or `:search-config?` in an options map on the command line it now works.  It also works if you put it in the `:zprint` key in a leiningen `project.clj` file or in the options map given to lein-zprint.  I had to reorganize quite a bit of code to make this work, but it was a good idea.  Thanks!
