### ISSUE TITLE
quote sign ' is printed as the symbol "quote"

### ISSUE THREAD

**Issue by daslu** [kkinnear/zprint#121]

**Comment by daslu** [comment]
Thank you for this beautiful and useful library.

I encountered the following behaviour:
```
user> (zprint.core/zprint '['x 'y])
[(quote x) (quote y)]
nil
```

It seems useful to be able to keep the `'` sign.

Also, ran across this related discussion at StackOverflow:
https://stackoverflow.com/questions/58308404/configure-symbol-quote-expansion-in-clojure-zprint

**Comment by kkinnear** [comment]
What an interesting idea!  Never occurred to me to worry about this, since `'` is handled with no problems formatting source.  Thanks very much for the link to the StackOverflow question and answer which points how how `pprint` does it.  I'm not wild about using `pprint` as the base printer for zprint, since I think that would pull in a lot of code that nobody really wants for a small gain -- but doing what it does for `quote` and maybe a bit more seems quite doable.

Thanks for the idea!

**Comment by daslu** [comment]
Thanks @kkinnear !

In the meantime, the following workaround seems quite handy:
```clojure
user>      (-> '['x 'y]
               clojure.pprint/pprint
               with-out-str
               (zprint.core/zprint 40 {:parse-string? true}))
['x 'y]
nil
```

**Comment by kkinnear** [comment]
Nice. 

I expect that I'll add the basic capability to zprint in the release after next.  It doesn't look hard (famous last words, of course).

**Comment by kkinnear** [comment]
Added this capability (optionally, as it happens) in 0.5.4.  Use `{:style :backtranslate}` to get this behavior when formatting structures.  Thanks for the idea -- and the pointer to how `pprint` did it, which helped me understand both what you wanted and how to implement it.
