### ISSUE TITLE
Preserving blank lines

### ISSUE THREAD

**Issue by agriffis** [kkinnear/zprint#125]
Would it be reasonable to add a configuration option for preserving blank lines? In my own code, if I don't have a blank link, I don't mind if zprint rearranges the newlines. But if I have a blank line, that's usually intentional, to break up blocks of code.

**Comment by kkinnear** [comment]
I have thought about that.  It certainly makes sense, and it has come up before as well.  I solved the previous persons issue by doing respect-new-lines, which they could configure for just a particular function.  I believe that it wouldn't be too difficult to add respect-blank lines (`:respect-bl?`) to go with respect-new-lines (`:respect-nl?`).  I think that `:respect-bl?` would be something that you could conceivably use for a whole file, not just for a particular function definition.    This is likely a whole lot easier than range formatting, for what that's worth.  At least the idea I have for how to do it would be a lot easier if it works out.  I'll put it on the list of things to look at.  

I'm guessing that the range formatting is more important to you than this, but if not, be sure and let me know because this would be a lot more fun to work on than the range formatting.

Thanks for asking!

**Comment by agriffis** [comment]
I don't mind if you work on this before range formatting...

Range formatting "works" now in vim-codefmt by sending only the top-level form to be formatted. The caveat is that zprint doesn't know about any `;!zprint` comments leading up to the form. For most files without special formatting needs, it's not a big deal, though it will be really nice to have it working properly eventually.

Preserving blank lines is something I'm doing manually now, for a few longer functions that deserve longer internal comments and some separation for readability. It would be great to avoid that manual step, and then I'd be more likely to use blank lines where appropriate, knowing that zprint would preserve them.

Thanks!

**Comment by kkinnear** [comment]
Added this in 0.5.4.  Use `{:style :respect-bl}`.  Thanks for the great idea!

**Comment by agriffis** [comment]
Thank you Kim. I wasn't working in Clojure for a while, so I hadn't tested this yet. `:respect-bl` is working well for me.
