### ISSUE TITLE
Auto Zprinting and integration?

### ISSUE THREAD

**Issue by webappzero** [kkinnear/zprint#15]
Thank you for zprint! As a new Clojure dev, I find zprint super helpful.

I'm curious if there are any known ways to setup zprint to work automatically at the repl. Or if there are any ways to hook it into existing tools, like Cider etc.

For example, currently, I can issue this command to see a zprinted function spec (one of my favorite uses).

```(zprint (clojure.spec/describe (clojure.spec/get-spec `function-name)))```

I'm curious what all would be involved in getting zprint to handle all output at the repl, or if that is a very bad idea for reasons I'm unaware of (performance comes to mind, but doesn't seem too critical at the repl).

i.e., being able to just issue the normal function call:

```(clojure.spec/describe (clojure.spec/get-spec `function-name))```

and have the result look nice.

I can ask the Cider folks about the editor issues, of course, but any thoughts or concerns you have about library, framework and editor integrations, in general, would be appreciated.

**Comment by kkinnear** [comment]
I haven't investigated how to integrate this directly into the repl, actually. That is an interesting idea. 

That said, you can see the specs of any function if you type (czprint-fn <fn-name>). It should find the specs and pretty print them in the doc string if the function was defined with defn. You will get the source to the function too, of course, as something of a bonus. Which might give you part of what you want. 

I'll look into how people have wired things into the repl.

**Comment by webappzero** [comment]
Thank you Kim. I'll close this issue since its very general. I'll keep an eye out for possible integration solutions myself and email you if I discover anything interesting. My best

**Comment by kkinnear** [comment]
So, I looked into this a bit.  There is a library called `greglook/whidbey` by the author of `puget`, an alternative to `zprint` which does colorized output.  `whidbey` does exactly what I think you want -- it replaces the printer for output to the repl.  There is a fair bit of mechanism required to do this, so I'm not going to jump in and replicate this for `zprint` anytime soon.  However, `whidbey` seems to work (during the 5 minutes I've spent playing with it).  

One option for you is to just use `whidbey` and let `puget` do your output.  I have used `puget` for a while and it does a fine job, though the default colors are not to my taste.  It doesn't do a number of other things quite the way I prefer (or I'd never have written `zprint`), but it might work fine for you.

In the fullness of time (which means that I will probably not get to it soon), I might figure out how to automatically connect `zprint` into `whidbey`.

Until I do that (or you figure out how to do it automatically and tell the rest of us), there is a **total hack** that will let you connect `zprint` into `whidbey` and use `zprint` instead of the `puget` printer for repl output.

First, follow the instructions for integrating `whidbey`, which means you put it into the leiningen plugins.  Then add `zprint` to your dependencies.

Then, when you start your repl, you should see the default `puget` colors for printing `[:a :b]`.  After you do the commands below, you will see the default `zprint` colors for printing `[:a :b]`.  

```clojure
user=> [:a :b]
[:a :b]
user=> (use 'zprint.core :reload)
nil
user=> (in-ns 'whidbey.repl)
#<clojure.lang.Namespace@151cd7b3 whidbey.repl>
whidbey.repl=> (def render-str zprint.core/czprint-str)
#'whidbey.repl/render-str
whidbey.repl=> (in-ns 'user)
#object[clojure.lang.Namespace 0x7a5ecdb8 "user"]
user=> [:a :b]
[:a :b]
```

If this isn't clear, please ask.  What you are doing above is substituting a `zprint` printing function for a `whidbey` printing function (which ultimately calls a `puget` printing function).

I have tested this for perhaps 2 minutes, but it does seem to work.  I may well use this myself.  If I do, I'll update this issue with any problems I find.  If you try it, feel free to add your experience here too.  Given the information in the `whidbey` readme, there might be some things that will give `zprint` trouble that come out at the repl, but I don't yet know of any.

All of the information in the `whidbey` readme about configuration (other than how to install it) will not be used in this case.  Whatever configuration you have created for `zprint` is what will be used.
