### ISSUE TITLE
Minor Issues with 1.0.0

### ISSUE THREAD

**Issue by RingMan** [kkinnear/zprint#150]
I've noticed a few small things in working with the 1.0.0 release. These are all on a Windows 10 machine. In no particular order:

1. The project file has minor formatting issues. A couple of lines use tabs instead of spaces to indent. A couple of others are just indented too far. I tried running `lein zprint` to fix the formatting, which leads me to...
2. `lein zprint` doesn't seem to like Windows line endings. I think it just threw some sort of exception. I then used vim to create a copy of the file with linux line endings. Then `lein zprint <file>` appeared to work, but didn't alter the original file. Instead, there was a temporary file left in the project directory with the formatted content.
3. Many elements use the :none key from the color map. Its default value is :black which means those elements are invisible on console windows with a black background. Since most users will want to customize their color scheme, it's not a big deal. But it's a less than ideal out-of-the-box experience.
4. As noted in #140, the tests that try to run multiple zprints in the same JVM don't appear to work on Windows
5. Previously, you could just run `lein test` from the command line. With the new project file, the leiningen `test` and `repl` tasks both require `with-profile +expectations` in order to find the expectations dependency. Adding back a :dev profile with just the `expectations` dependency fixes that.
6. Running `czprint-fn` on source code that has `##Inf`, `##-Inf`, or `##NaN` will throw an exception. This is due to the rewrite-clj parser, not zprint, but ideally zprint should be able to format any legitimate Clojure source file. There's an old [issue](https://github.com/xsc/rewrite-clj/issues/75), but I'm not sure how active the project is.

Thanks for this excellent library. Pretty printing in color makes the REPL experience so much more productive and enjoyable.

**Comment by kkinnear** [comment]
Thanks for all of these issues. I’ll get back to you tomorrow about many of them. I appreciate the time you spent noticing these things. It is easy for me to miss things, and another set of eyes always helps! 

More later.

**Comment by kkinnear** [comment]
Lots to deal with here...

1. I forgot to format the project.clj file. I should add that to my notes. 

2. Two problems. The windows line endings I expect (hope) I can diagnose myself. The file handling is going to be a challenge. I use a library to do the file handling in lein zprint. I presume you didn’t get a file with a `.old` extension?  If so, that’s not a bug. But if not, as I expect, then that’s a problem. I don’t have access to a windows system these days. So that’s going to be a challenge. 

3. Yes, I agree about the black background. I have been around long enough that I grew up with terminals with green letters — orange was a great advance —  so I’m not a dark background person.  I think a style which is nice for a dark background would be a great idea. Probably needs to be based on the color work you did.  I could also see a default that was dark but not black if you color work has something like that available. 

4. I think the issue is where there are two zprints running simultaneously. That is interesting and concerning, since it means that probably does not work on windows either. But I don’t n is what to do about that other than document it. 

5. I was having trouble tearing shadow-cljs so I was looking at my `Pom.xml` file and found all of my `:dev` dependencies in there, under “scope test”. Which annoyed me, since as I read the Leiningen docs they aren’t supposed to be there at all.   Probably not a problem, but I wanted to get them out of there.   

  That said, I just do `lein repl` and it works fine. Now, I don’t use expectations from the repl, so maybe that’s why.     

All of that said, I can see having expectations in a `:dev` dependency, as that will not annoy me if it shows up in the pom.

I’m sorry to trip you up. I should write a contributing section of the docs, where I can talk about testing and, I suppose, the entire release process which is somewhat involved. 

6. Yes, rewrite-clj needs some work, and I haven’t been excited about doing it myself. 

  I agree that zprint should work on anything that is legal Clojure. I’ll have to look at these things and see if there is anything I can do to work around this limitation. If you have some real code that doesn’t work, I would be glad to work with that in addition to my own tiny tests to work on this.

**Comment by RingMan** [comment]
I think adding a contributing section in the docs is a great idea, perhaps with some guidance on submitting Issues and submitting Pull Requests. For example, here I just aggregated everything into a single issue, leaving it to you to split things out if necessary. This was partly because I'm not sure what your preferences are for creating issues.

BTW, for my use case (playing around at the REPL), the items above are at worst a minor inconvenience. But since I noticed, I thought I would pass it along.

2. I did not get a `.old` file, but there was a randomly named file with the formatted content in it.

3. I remember those monitors as well.

4. I think documenting it is fine. The only reason I even noticed is that I was running the tests to see if I had broken anything. If it's an OS-specific issue, it could also make sense to bypass those tests on Windows.

5. I usually just do `lein repl` as well. The only reason it was an issue for me was because I like to use integrant to reload code at the repl. When I ran `(reset)` it tried to load the testing namespaces and couldn't.

6. I don't have any real code that uses symbolic values. For exercising `czprint-fn`, something as simple as `(def positive-infinity ##Inf)` in a source file reveals the issue. If you call rewrite-clj's `parse-string` directly, even just `(parse-string "##Inf")` will do the trick. One possible work-around would be to pre-process source strings before calling `parse-string`. You already do this for tab expansion. Anyway, if you could transform symbolic values to tagged literals, you could transform them back when printing. For example, if you call `(parse-string "#zprint/symbolic-value \"##Inf\"")` you'll get a ReaderMacroNode. Its children will contain a TokenNode with zprint/symbolic-value and a StringNode with `##Inf`. The transformation function would need to preserve `##Inf` in strings and comments, so it's definitely not trivial.

**Comment by kkinnear** [comment]
I haven't dealt with all of this, but here are a few things:

 1. For the ##Inf Clojurescript stuff I'm currently planning to wait until rewrite-cljc gets finished, and use that to solve this problem.  

2. The next release of lein-zprint (tomorrow) will have completely different file handling, so let me know if the it works on Windows, if you would.  I think it has a chance of working.

Thanks, I'll keep working on the rest of this.

**Comment by kkinnear** [comment]
Several things (numbers bear no relation to previous scheme):

1. I can't seem to reproduce the problem with Windows line endings.  If I put in a file with `\r\n` line endings, it seems to format fine (and comes out with `\n` line endings, which is not great).  I can't get `lein zprint` to fail, either `1.0.0` or `1.0.1`.  So this is going to be a challenge to debug.  Could you perhaps try this with `1.0.1` and maybe send me the file that doesn't work?

2. `lein zprint` rename not working -- as I said above, please try this with `1.0.1` and see how the new code works.

3. I still forgot to format the `project.clj` file.  I have actually now added that information to my release instructions.  Sigh.

4. Now you can't run `lein test` at all, since I converted the tests to `expectations/cljc-test` which doesn't yet exist in a downloadable release.  I ported `expectations/clojure-test` to Clojurescript, and the changes got in, but it hasn't yet released.
You would have to build it yourself in order to run the tests.  Moreover, having `expectations/cljc-test` in the `pom.xml` file did cause a problem with `cljdoc`, so now it is broken.  So I have to rework the `project.clj` file to get it out of the `pom.xml`.  

5. I haven't dealt with multiple JVM's in tests (though of course the cljs versions of the tests don't do that).  I haven't figured out what to do about that for Window's testing.

**Comment by RingMan** [comment]
I have more info on `lein zprint` in a Windows environment. With one exception, it works for files with dos, unix, and mac line endings (including renaming the file if `:old?` is truthy).  The exception is any file that has a comment with a windows-style line ending.  As you mentioned, the resulting file always has unix-style line endings.

After debugging this for a bit, the issue is in the `zprint-file-str` function.  Here's the simplest input that causes it to fail:

````clojure
user=> (zp/zprint-file-str ";\r\n" "comment with crlf")
AssertionError Assert failed: (string-of? s r/linebreak?)  rewrite-clj.node.whitespace/newline-node (whitespace.clj:89)
````

The patch below fixes the issue. First, it splits lines using any of the three eol sequences.  Second, it replaces unix line separators with the host system's line separator in the final output.

````diff
diff --git a/src/zprint/core.cljc b/src/zprint/core.cljc
index d4b6f36..90062a2 100644
--- a/src/zprint/core.cljc
+++ b/src/zprint/core.cljc
@@ -1138,7 +1138,7 @@
        ; Make sure to get trailing newlines by using -1
        (let [; If the filestring starts with #!, remove it and save it
              [shebang file-str] (remove-shebang file-str)
-             lines (clojure.string/split file-str #"\n" -1)
+             lines (clojure.string/split file-str #"\r\n|\r|\n" -1)
              lines (if (:expand? (:tab (get-options)))
                      (map (partial expand-tabs (:size (:tab (get-options))))
                        lines)
@@ -1205,10 +1205,13 @@
              out-str (if range
                        (reassemble-range before-lines out-str after-lines)
                        out-str)
-             out-str (if shebang (str shebang "\n" out-str) out-str)]
-         (if (and ends-with-nl? (not (clojure.string/ends-with? out-str "\n")))
-           (str out-str "\n")
-           out-str))
+             out-str (if shebang (str shebang "\n" out-str) out-str)
+             out-str (if (and ends-with-nl?
+                              (not (clojure.string/ends-with? out-str "\n")))
+                       (str out-str "\n")
+                       out-str)]
+         (clojure.string/replace
+           out-str "\n" (System/getProperty "line.separator")))
        (finally (reset-options! original-options original-doc-map)))))
   ([file-str zprint-specifier new-options]
    (zprint-file-str file-str
````

The second behavior is reasonable, but I think a better choice is to let the user specify the desired line endings in the formatted output. The setting could be named something like `:output-eol` with a value from the set `#{:cr :lf :crlf :host-env :file}`.
I could also imagine values from the set `#{:unix :linux :mac :macintosh :win :windows :dos}`. The first three values choose a target line ending independent of the current OS or selected file. The `:host-env` value would use the `line.separator` for the host environment as in the patch above. The `:file` value would use the same line endings as in the original file.

That last option requires determing the eol style of the input file. That's not too bad if all the endings are the same. Where it gets interesting is if there's a mixture of styles. Here, you could just choose the one used most often or report an error and quit.

**Comment by RingMan** [comment]
I was able to run `lein test` by cloning `kkinnear/clojure-test` and adding the following alias to its `deps.edn` so I could install it locally:

````clojure
:install
{:extra-deps {deps-deploy/deps-deploy {:mvn/version "0.0.9"}}
 :main-opts ["-m" "deps-deploy.deps-deploy" "install" "expectations.jar"]}
````

With WSL 2 running Ubuntu 20.04, `lein test` succeeds. Tests also pass when splitting file strings on any line ending. On Windows, two of the tests that use `with-out-str` still fail, but I'm submitting a pull request with a fix.

**Comment by kkinnear** [comment]
Wow, go you for getting the testing framework working!  That's very impressive!

Thank you for all of your work to figure things out. I'm pleased that the file renaming (which isn't really renaming anymore) now works on Windows.

You have certainly pinpointed the major problem with the incoming line endings, but I'm wondering what zprint should do with strings with line-endings in them when `:parse-string-all?` is used instead of `zprint-file-str`.  I'm going to have to look a `:parse-string-all` and its relationship to `zprint-file-str`.  I may need to deprecate `:parse-string-all?`.  Anyway, thanks for finding this comment issue with `rewrite-clj` and such a nice fix for it.

Good thinking about how the tests would all fail if the strings didn't have `\n` line endings.  

I'm not sure that doing `line.separator` is going to be a viable option in cljs, though I will check and it is a pleasing thought.  Without having put too much thought into it, I'm thinking that having `zprint-file-str` do on output what it received on input would be a reasonable thing to do.  Then all of the existing tests would pass, and any new tests could test that new behavior.

There are already so many configuration options, do you really think letting people specify the line endings seems like a worthwhile thing to do?  It probably wouldn't be that hard as long as we are already having to (maybe) change them just to make them like what came in.  Would you actually use that capability?

As you point out, determining what __was__ input isn't trivial, but I would lean toward looking at the first 10 line endings and taking the majority approach there.  Either that or just using majority of the second, third and fourth line endings.  Or something like that.  No way I'm looking at the whole file to figure out the line endings. 

Anyway, thank you for continuing to work through these issues, I really appreciate it.

**Comment by RingMan** [comment]
Thank you for the kind words.  It's really no problem. I'm just glad I can make a small contribution to the quality library you've worked so hard to produce.

I think your suggestion of using the same EOL style as the input is actually the most natural behavior and presents the least surprises. We _expect_ the layout to change, but not necessarily the EOL style. No option needed. In the rare case the user wants different line endings, the readily available `dos2unix` and `unix2dos` tools make it trivial.

I also think just sampling a handful of line endings works just fine. Most of the time they will all match. The few times I've seen mixed line endings, there was always a clear winner.

**Comment by kkinnear** [comment]
I'm working to get the line ending fixes to work across the whole product, and I'm wondering why you added `"\r" to this regex:

```
+             lines (clojure.string/split file-str #"\r\n|\r|\n" -1)
```

Do you know of an actual instance of people having simply `"\r"` as a line ending?  I'm trying to minimize the performance hit in the additional processing around line endings.

Thanks!

**Comment by RingMan** [comment]
I looked into it a little bit. Best I can tell, the classic Mac OS (through version 9) used `\r` as the line ending. Mac OS X is a Unix and uses `\n` like other Unix systems. So `\r` is probably not that relevant for modern systems. That said, it _is_ a legit ending. I think most programming editors (and utilities like Notepad++) can handle all three styles.

**Comment by kkinnear** [comment]
The line endings are now preserved in 1.0.2.  Thanks for your help in dealing with these.  Also your help with the colors and dark themes, also in 1.0.2.

You now need to run `lein with-profile expectations test` again, since without that, the SNAPSHOT version of `expectations/clojure-test` shows up in `pom.xml` and then `cljdoc` doesn't work.  Sigh.

**Comment by kkinnear** [comment]
As far as I know, this issue has been resolved.  Thanks again for your help.
