### ISSUE TITLE
`:respect-nl?` oddity

### ISSUE THREAD

**Issue by atdixon** [kkinnear/zprint#162]
A simple use of `:respect-nl?` will cause the arguments to stagger:

```
$ echo -e "(foo 1\n2\n3\n4)" | ./zprintm-1.0.1 '{:list {:respect-nl? true}}'
(foo 1
       2
     3
       4)
```

This is also reproducible with `zprintm-1.0.2`.

**Comment by kkinnear** [comment]
Thanks for asking!

What is happening in this example (and, presumably, in some realistic situation you have encountered) is that you are seeing what is known as ["constant-pairing"](https://github.com/kkinnear/zprint/blob/master/doc/reference.md#constant-pair-true). The link will give you more than you probably wanted to know about it, but the short story is that often the end of a list has constants and then values and then constants and then values.  Constant-pairing will recognize these situations, and treat them as "pairs", and then do whatever formatting is configured for "pairs".  By default, if the second element of a pair (say in a `cond` or locals in a `let`) don't fit on the line where the first element of the pair is located, the second element will be indented.  You are seeing the second elements of the constant-pairs being indented, which is explained [here](https://github.com/kkinnear/zprint/blob/master/doc/options/pairs.md).

For what it is worth, constant-pairing has yielded some amazing benefits -- for instance,  by itself it causes specs to come out more readably than any other formatter.

Anyway, if this behavior is causing your code or data to look bad, there are two ways you can change it.

1. Turn off constant pairing.
2. Change the indent on pairs to 0, which will still keep constant-pairing, but remove the indent from the second element if they are on different lines.

Here is an example of 1, above (done at the REPL, which is why you see the `:parse-string? true`):
```
zprint.core=> i160
"(foo 1\n2\n3\n4)"
zprint.core=> (czprint i160 {:parse-string? true :list {:respect-nl? true}})
(foo 1
       2
     3
       4)
nil
zprint.core=> (czprint i160 {:parse-string? true :list {:respect-nl? true :constant-pair? false}})
(foo 1
     2
     3
     4)
nil:
```
Here is an example of 2:
```
zprint.core=> (czprint i160 {:parse-string? true :list {:respect-nl? true} :pair {:indent 0}})
(foo 1
     2
     3
     4)
nil
```
Either change can be made for all uses of zprint by putting one or the other of these into the `~/.zprintrc` file.  

Alternatively, you can have this behavior turned off only when formatting a specific function, like this:
```
zprint.core=> (czprint i160 {:parse-string? true :list {:respect-nl? true} :fn-map {"foo" [:none {:list {:constant-pair? false}}]}})
(foo 1
     2
     3
     4)
```
This says: When formatting a function named "foo" use the options-map `{:list {:constant-pair? false}}` when formatting all of the contents of "foo", but not anywhere else.  You could also use an options-map of `{:pair {:indent 0}}` instead in the options-map associated with the function "foo" and get the same effect on constant pairing, without wiping out the good things that constant-pairing gives you.

I hope this explains things clearly enough.  Thanks for asking, and if these two approaches don't seem like they will adjust the formatting to your liking (or you have any other issues configuring zprint), please don't hesitate to ask!  Thanks!

**Comment by atdixon** [comment]
Thanks for this explanation, very helpful!

**Comment by kkinnear** [comment]
I don't think there was anything else here to say.  Feel free to reopen this or log a new issue if you have questions or concerns!
