### ISSUE TITLE
macOS already has a zprint executable: mach_memory_info: (os/kern) invalid host on Mac

### ISSUE THREAD

**Issue by agzam** [kkinnear/zprint#174]
I installed the cli on Mac with OS X Big Sur and running it throws the error:

    zprint: mach_memory_info: (os/kern) invalid host (try running as root)
    

it works with sudo, but that makes it difficult for me to use it from Emacs. Is there any work around this thing?

**Comment by agzam** [comment]
Ooops... turned out that I was running the wrong zprint. It seems Mac comes with BSD zprint, running 
`man zprint` says: `zprint -- show information about kernel zones`.

I had to manually rename zprint's executable  `mv /usr/local/bin/zprint /usr/local/bin/zprintm`

**Comment by kkinnear** [comment]
Hey, thanks for the heads up.  I leave my zprint executables as `zprintm-1.1.1` or whatever, so I can tell them apart, so I never ran into this.  Turns out that zprint is a thing on Mojave and Big Sur (the only versions I have access to presently).

I'm going to re-open this issue to remind me to add this information to the macOS documentation to save someone else the confusion of finding out that there is already a zprint. 

Thanks again for letting me know about this!

**Comment by kkinnear** [comment]
I updated the docs for this in `1.2.4.  Thanks for pointing it out!
