### ISSUE TITLE
How to format better-cond macro?

### ISSUE THREAD

**Issue by lucywang000** [kkinnear/zprint#178]
Hi, I'm trying to use zprint to format the [better-cond](https://github.com/Engelberg/better-cond) macro. Taking the demo from its README as an contrived example:

```clojure
(b/cond
   (odd? a) 1

   :let [a (quot a 2)]
   ; a has been rebound to the result of (quot a 2) for the remainder
   ; of this cond.

   :when-let [x (fn-which-may-return-falsey a),
              y (fn-which-may-return-falsey (* 2 a))]
   ; this when-let binds x and y for the remainder of the cond and
   ; bails early with nil unless x and y are both truthy

   :when-some [b (fn-which-may-return-nil x),
   			   c (fn-which-may-return-nil y)]
   ; this when-some binds b and c for the reaminder of the cond and
   ; bails early with nil unless b and c are both not nil

   :when (seq x)
   ; the above when bails early with nil unless (seq x) is truthy
   ; it could have been written as: (not (seq x)) nil

   :do (println x)
   ; A great way to put a side-effecting statement, like a println
   ; into the middle of a cond

   (odd? (+ x y)) 2

   3)
```

How could I make zprint to properly format the nested `:let` `:when-left` forms inside it?

**Comment by kkinnear** [comment]
Hello!  Thanks for asking!  I'm a little confused, so perhaps you could help me out here.  One of zprint's "features" is that it formats (or is supposed to format) the better-cond correctly.  The example you give above formats like this for me using `zprint 1.1.1`:
```Clojure
./zprintm-1.1.1 '{:style :respect-bl :list {:indent 3}}' <i178.clj
(b/cond
   (odd? a) 1

   :let [a (quot a 2)]
   ; a has been rebound to the result of (quot a 2) for the remainder
   ; of this cond.

   :when-let [x (fn-which-may-return-falsey a)
              y (fn-which-may-return-falsey (* 2 a))]
   ; this when-let binds x and y for the remainder of the cond and
   ; bails early with nil unless x and y are both truthy

   :when-some [b (fn-which-may-return-nil x)
               c (fn-which-may-return-nil y)]
   ; this when-some binds b and c for the reaminder of the cond and
   ; bails early with nil unless b and c are both not nil

   :when (seq x)
   ; the above when bails early with nil unless (seq x) is truthy
   ; it could have been written as: (not (seq x)) nil

   :do (println x)
   ; A great way to put a side-effecting statement, like a println
   ; into the middle of a cond

   (odd? (+ x y)) 2

   3)
```
Which, near as I can tell, is almost the same as what you have above [after I corrected the second element of the when-some in your example] except that it doesn't have commas between the elements of the `:let` and the `:when-some`.  The normal `:list :indent` for zprint is 2, not 3, and normally it will elide blank lines, yielding this by default:
```clojure
./zprintm-1.1.1 <i178.clj
(b/cond
  (odd? a) 1
  :let [a (quot a 2)]
  ; a has been rebound to the result of (quot a 2) for the remainder
  ; of this cond.
  :when-let [x (fn-which-may-return-falsey a)
             y (fn-which-may-return-falsey (* 2 a))]
  ; this when-let binds x and y for the remainder of the cond and
  ; bails early with nil unless x and y are both truthy
  :when-some [b (fn-which-may-return-nil x)
              c (fn-which-may-return-nil y)]
  ; this when-some binds b and c for the reaminder of the cond and
  ; bails early with nil unless b and c are both not nil
  :when (seq x)
  ; the above when bails early with nil unless (seq x) is truthy
  ; it could have been written as: (not (seq x)) nil
  :do (println x)
  ; A great way to put a side-effecting statement, like a println
  ; into the middle of a cond
  (odd? (+ x y)) 2
  3)
```
Since you wouldn't have opened an issue if zprint already did what you want, I suspect that the output above isn't to your liking, but I'm not sure just what you would like to see from zprint?  

Is the problem that you want commas in the `:let` and `:when-come`?  That can't be configured today, but it would certainly be possible to add.  At present zprint doesn't do commas in any of the binding forms like `let`.  But it certainly could be extended to do so.

I'm thinking, though, that there is something else other than the commas that you would like zprint to do that it isn't doing for you today.  Please let me know what you would like the above example to look like, and I'll let you know how to configure zprint to do that if it is possible, and we can see about extending zprint if it isn't possible.

Thanks!

**Comment by kkinnear** [comment]
Hmmm.  If you are looking for get zprint to format the better-cond 2.0 where you use non-keyword `let`, etc., that isn't something it will do today. 

> As of version 2.0.0, writing let, when-let, when-some, when, and do as keywords is optional. So you can also write it like this, if you prefer:

```clojure
 (cond
   (odd? a) 1
   let [a (quot a 2)]
   when-let [x (fn-which-may-return-falsey a),
             y (fn-which-may-return-falsey (* 2 a))]
   when-some [b (fn-which-may-return-nil x),
              c (fn-which-may-return-nil y)]
   when (seq x)
   do (println x)
   (odd? (+ x y)) 2
   3)
```
This is what you get from zprint when formatting the above code:
```clojure
./zprintm-1.1.1 <i178a.clj
(cond (odd? a) 1
      let [a (quot a 2)]
      when-let [x (fn-which-may-return-falsey a) y
                (fn-which-may-return-falsey (* 2 a))]
      when-some [b (fn-which-may-return-nil x) c (fn-which-may-return-nil y)]
      when (seq x)
      do (println x)
      (odd? (+ x y)) 2
      3)
```
which is far from optimal in the binding forms.  In this case, I would suggest using the keyword forms of let, etc. 

Let me know if you are trying to get zprint to format this non-keyword form of better-cond.  I can imagine how to format that correctly with a new capability that I am even now creating, but it will be a while yet before it gets released.

**Comment by lucywang000** [comment]
@kkinnear Thanks a ton for the detailed reply!  So far It addressed most of my questions.

My remaining questions:
1. What if I want to place the `:when`/`:do` keyword on the same line with its binding clauses, but keep the condition pairs on different lines? e.g

```clojure
(b/cond
  :when (not= x 100)
  (> x 1)
  :some-return-value

  (< x 1)
  :some-other-return-value
```

Note the `:let` `:when-let` binding keywords is always on the same line with the clauses, which is good. But the `:when` `:do` keywords would be forced to the next line if I use `{:pair {:flow? true}}`

2. I have a custom macro that wraps the `b/cond` macro which adds a binding clause in the first argument, i.e.:

```clojure
(my-wrapper-macro [<bindings>]
    <... other b/cond pairs ...>
)
```

For instance:

```clojure
(my-wrapper-macro [x1 v1
                                     x2 v2]

    :let [inner-x1 v1]
     (> x1 1)
     :some-return-value

      (< x1 1)
      :some-other-return-value
)
```

How should I make zprint recognize its first argument is a binding vector, and the rest are `b/cond` like?

**Comment by kkinnear** [comment]
I'm glad you found my answer helpful.  

To answer your first question -- there is no way, at present, to keep the `:do` and `:when` on the same line when you use `{:pair {:flow? true}}`, since zprint does not recognize `:do` and `:when` as anything special.  If there is a keyword with a vector following, it recognizes that and processes it differently then a regular pair, but a simple keyword at present is processed as just another left-hand part of a pair.  I can make a simple change which will almost certainly not cause anyone to see a behavior change which will make zprint recognize any keyword which also appears in the `:fn-map` as special, which would generate the behavior you want.  I will make this change in the next release, `1.1.2`.

Your second question will also require a small internal change to be able to get the behavior you desire.  However, I have found a truly contorted way to generate most of what you want.  It requires you to use `{:list {:respect-nl? true}}` which means that to get the newlines you want, you will have to put them in yourself and have zprint "respect them", by setting `:respect-nl? true`.  Once I make the small change, it will be much simpler to get what you want for this macro, and I will make that change in `1.1.2` as well.

For now, this is what you can do:
```
(print i178c)
(my-wrapper-macro [x1 v1
                   x2 v2]

    :let [inner-x1 v1 inner-x2 v2]
     (> x1 1)
     :some-return-value

      (< x1 1)
      :some-other-return-value
)

(czprint
  i178c
  {:parse-string? true,
   :fn-map {"my-wrapper-macro"
              [:arg1-pair
               {:list {:respect-nl? true},
                :vector {:option-fn-first
                           (fn [options sexpr]
                             {:vector {:fn-format :arg1-force-nl},
                              :vector-fn {:constant-pair-min 1,
                                          :constant-pair-fn any?,
                                          :indent 1,
                                          :hang? false},
                              :pair {:force-nl? true},
                              :next-inner {:vector {:option-fn-first nil}}})},
                :next-inner {:list {:respect-nl? false}}}]}})
(my-wrapper-macro [x1 v1
                   x2 v2]

  :let [inner-x1 v1
        inner-x2 v2]
  (> x1 1)
    :some-return-value

  (< x1 1)
    :some-other-return-value
)
```
This is what you would put into a `~/.zprintrc` or `zprint.edn` file for "my-wrapper-macro":
```
{:fn-map {"my-wrapper-macro"
            [:arg1-pair
             {:list {:respect-nl? true},
              :next-inner {:list {:respect-nl? false}},
              :vector {:option-fn-first
                         (fn [options sexpr]
                           {:vector {:fn-format :arg1-force-nl},
                            :vector-fn {:constant-pair-min 1,
                                        :constant-pair-fn any?,
                                        :indent 1,
                                        :hang? false},
                            :pair {:force-nl? true},
                            :next-inner {:vector {:option-fn-first nil}}})}}]}}
```
This starts by saying that the macro should have its first argument on the same line as the macro name and to format the inside of the macro as a set of pairs.  Then it says to respect newlines in lists (and removes that for other than the top level of the macro).  Then it gets interesting.  It says for every vector, format that vector as a list where the first two things are on the same line, and the other things are "constant pairs" because anything `(any? ...)` can be a constant. But don't put the pairs on the same line.   More or less.

If you find this confusing, I'm not surprised.  It took me about 1.5 hours to get to this.  And it still isn't quite right.  Things will be much better after I make both the small changes I discussed above, but for now, this is the best I can do.  I will update this issue with how to do it in `1.1.2` when that releases (which will be several weeks, but probably not more).

Thanks for asking!

**Comment by lucywang000** [comment]
@kkinnear Amazing! 

> If you find this confusing, I'm not surprised. It took me about 1.5 hours to get to this

Yeah I have to say this is confusing, maybe the most confusing part of the zprint docs. I have read things like`[:arg1-pair  {:list {:respect-nl? true} ... }]` in the [reference.md](https://github.com/kkinnear/zprint/blob/master/doc/reference.md) file but was not able to get much out of it. You literal translation it into English is much better 😂

**Comment by kkinnear** [comment]
This is what it will take to do the basics of what you want in `1.1.2` (though it doesn't handle blank lines like you want yet):
```
(czprint i178c
         {:parse-string? true,
          :fn-map {"my-wrapper-macro"
                     [:binding
                      {:list {:constant-pair-min 1, :constant-pair-fn any?},
                       :next-inner {:list {:constant-pair-min 2,
                                           :constant-pair-fn nil}}}]}})
(my-wrapper-macro [x1 v1
                   x2 v2]
  :let [inner-x1 v1
        inner-x2 v2]
  (> x1 1) :some-return-value
  (< x1 1) :some-other-return-value)
```
Not pretty, but much simpler. The `:binding` fn-type is what your macro wants to use, but today in `1.1.1` the remainder of the forms in the `:binding` fn-type don't know about constant pairing, and so this doesn't work (yet).  It wasn't a lot of work to get the `:binding` fn-type to use the right routine for the rest of the forms so that constant pairing would work there, which I have done in my development sandbox and used to create this example.

I'll let you know when `1.1.2` is released by updating this issue.

**Comment by lucywang000** [comment]
Thanks a lot, looking forward to it!

**Comment by kkinnear** [comment]
I have fixed up the `:binding` fn-type to handle constant pairs, so that this simpler approach may give you what you want when formatting "my-wrapper-macro".  At least I hope so.  

In particular, I have also fixed `:when` and `:do` to stay on the same line even when `:nl-separator-all?` is true.  If this isn't what you are looking for, let me know what you would like, and I'll see what I can figure out.
```
zprint.core=> (print i178g)
(my-wrapper-macro [x1 v1
                   x2 v2]

    :let [inner-x1 v1 inner-x2 v2]
     (> x1 1)
     :some-return-value
       :when (not= x 100)


      (< x1 1)
      :some-other-return-value
)
nil
zprint.core=>
(czprint i178g
         {:parse-string? true,
          :fn-map {"my-wrapper-macro"
                     [:binding
                      {:list {:constant-pair-min 1, :constant-pair-fn any?},
                       :pair {:flow? true, :nl-separator-all? true},
                       :next-inner
                         {:list {:constant-pair-min 2, :constant-pair-fn nil},
                          :pair {:flow? false, :nl-separator-all? false}}}]},
          :style :community})
(my-wrapper-macro [x1 v1
                   x2 v2]
  :let [inner-x1 v1
        inner-x2 v2]

  (> x1 1)
  :some-return-value

  :when (not= x 100)

  (< x1 1)
  :some-other-return-value)
```

**Comment by kkinnear** [comment]
`1.1.2` was released a long time ago.  This should be working now.  If it is not what you want, please re-open this issue.  Thanks.
