### ISSUE TITLE
Normalization or permissiveness

### ISSUE THREAD

**Issue by pesterhazy** [kkinnear/zprint#18]
I read this interesting [comment](https://news.ycombinator.com/item?id=13371999) describing how gofmt works and though it might be worth bringing up for discussion. I think gofmt is a very useful model to look at because it has won the hearts of the golang community.

Basically a code re-formatter could take one of two approaches:

*Normalization*: transform the input into an AST and reformat from scratch, disregarding all original whitespace.

*Permissiveness*: preserve some of the original whitespace. As explained in the comment I linked to, sometimes an unusual newline is introduced on purpose.

A (not very good, admittedly) example might be:

```
(defn square 
   [a]
   (* a a))
```

Where the normalizer would reformat this

```
(defn square [a]
   (* a a))
```

the permissive reformatter would take the newling as a hint and keep the linebreak (but would perhaps coalesce two subsequent linebreaks).

The normalization approach seems more "clean" from an implementation perspective (modulo comments?), but the second one could make more people happy with the results. Any thoughts on this distinction?

**Comment by kkinnear** [comment]
An excellent question, certainly worthy of discussion.  Obviously, zprint was written to be in the _normalization_ camp.  The _permissive_ approach for Clojure is essentially something that correctly indents what you have, but doesn't mess with the line breaks.  Because you (presumably) put those line breaks in there for a reason.  The reason that zprint exists is (well, actually, I was working on a REPL-based editor, see, and needed to get the code to fit into a fairly narrow-ish window and still be readable, and ... then the possibility of really doing complete formatting took over about 18 months ago and the editor went by the wayside and here we are).  Anyway, the reason zprint exists as something that you can use is precisely because I wanted something that would do a great job at the normalization problem.  Personally, I actually like Lisp syntax, but I don't like formatting it myself.  I also find that the cognitive load is decreased if I can see more functions (or more of one function) at the same time on the screen.  So I built zprint to use the space (width) effectively while still making the code look good.

Also, zprint is actually pretty heuristic about how it does things -- there are tuning parameters which govern hang and flow, in particular, to try to make it look good.  To pick up on a theme from the HN comment you referenced.

As it happens [cljfmt](https://github.com/weavejester/cljfmt) already exists to do the permissive thing for Clojure code in files.  It doesn't work at the REPL, but does files well.  I haven't looked too carefully at the details, because I think it is pretty permissive with the line breaks (that is, it doesn't mess with them when I tried it).  But the example in the readme showed it changing the line breaks, so I don't know exactly what to believe.  But I am pretty sure that while it might normalize a small amount, it is _mostly_ permissive.  If someone wants permissive for Clojure, for files at least, that is your best bet.  It also uses `rewrite-clj` to parse the source, as does zprint.  It is also truly lovely, and terribly concise code.  It made me want to spend another year cleaning up zprint just so it might look 1/4 as good as cljfmt.  But that didn't seem like it would do anyone much good in the long run, so I resisted that temptation.   I have a huge amount of respect for cljfmt, but it doesn't do what I wanted.

So, to be clear, zprint was designed totally intentionally to be a normalizing Clojure code formatter.  That said, I have _also_ designed it to be extraordinarily configurable, so that while it will format code the way that it wants to, ignoring all of your whitespace, anyone can exert a large amount of control over _the way it wants to_.  And even change that in a file for just one function or for the whole file.

All that said, I'm not against adding some level of permissive formatting (though that isn't easy, since ignoring whitespace is built in at a very low level), if I knew when to be permissive and when not.  But how do you tell zprint that _this_ new-line is intentional and all of the others aren't?  I think that is the problem.

So, I think there are two ways to go here:

1. zprint does the normalization space, and cljfmt does the permissive space.  Pick the way you want to do it, and use that tool.

2. Try to move some (focused, small) level of permissive formatting into zprint.

I'm willing to explore #2 with you if you want to go there, but absent your coming up with some use cases and ways to make it work (i.e., answering the question: how do I know this new-line is the one you want), I'm probably going to continue to move forward on the myriad of things that I think zprint could do that it does not now.  For example, if I can get it to work in self-hosted Clojurescript, I might be able to build a [lumo](https://github.com/anmonteiro/lumo) standalone formatter which would start up instantly and integrate better into at least my editing environment (and be useful for others, I expect, too).  But that's just one of the many things that are hanging out on my todo list.  Others are exploring a way to improve the performance (I've got one possible idea that might make a substantial difference, but I need to prototype it), and simple things like letting you specify the color of map keys for some particular keys.

Anyway, thanks for bringing it up!

**Comment by pesterhazy** [comment]
Great summary. I think I agree with you on all points.

Personally, normalization seems to work well so far. In fact I haven't into a situation where I hoped for a more permissive behavior yet. My question is answered so I'll close this issue, but I think your comment is actually useful documentation on the philosophy behind zprint.
