### ISSUE TITLE
:interpose broken in uberjar and binaries when configured in .zprintrc files

### ISSUE THREAD

**Issue by mapidentity** [kkinnear/zprint#186]
Using homebrew installed zprint-1.1.1

Given $HOME/.zprintrc containing `{:search-config? true}`
And $PWD/.zprintrc containing `{:parse-string-all? true :parse {:interpose "\n\n"} :width 120}`

The following command:
```sh
echo "(def a :b) (def c :d)" | zprintm
```
Gives output:
```clojure
(def a :b)(def c :d)
```

But command:
```sh
echo "(def a :b) (def c :d)" | zprintm "$(cat .zprintrc)"
```
Gives output:
```clojure
(def a :b)

(def c :d)
```

The latter is the output I would expect. Why is this different? For completeness, `zprintm -e` gives:
```clojure
{:parse {:interpose {:set-by ":search-config? file: /Users/someuser/someproject/.zprintrc",
                     :value "\n\n"}},
 :parse-string-all? {:set-by ":search-config? file: /Users/someuser/someproject/.zprintrc",
                     :value true},
 :search-config? {:set-by "Home directory file: /Users/someuser/.zprintrc", :value true},
 :width {:set-by ":search-config? file: /Users/someuser/someproject/.zprintrc", :value 120}}
```

**Comment by kkinnear** [comment]
Thanks for noticing this and creating an issue!   Particular thanks for doing the `zprintm -e` output, as that was key in my uncovering what is going on with this rather humbling bug. 

I'll have more to say about it tomorrow, but I wanted to give you the workaround that I found:

If you include an empty options map on the command line, it should work correctly:
```
% more .zprintrc
{:parse {:interpose "\nxxx\n"} :color? true :width 80}
% echo "(def a :b) (def c :d)" | ./zprintm-1.1.1
(def a :b)(def c :d)
% echo "(def a :b) (def c :d)" | ./zprintm-1.1.1 '{}'
(def a :b)
xxx
(def c :d)
```
I added some useless characters to the `:interpose` because I got tired of counting empty lines while debugging this.

More later...

**Comment by mapidentity** [comment]
Thank you for responding so promptly and providing a workaround!

**Comment by kkinnear** [comment]
Thanks again for noticing this.  It turns out that when I added the URL configuration capability about a year ago, I had to conceptually split some of the options into "operational" option -- those that control configuration, and "format control" options -- those that affect configuration. When rewriting the main program used in the pre-built binaries and the uberjar I managed to leave out the step that configures the formatting options from the `.zprintrc` files.   This all worked prior to release `0.5.4`. 

There are tests that check for configuration from the `.zprintrc` files, but they continued to work since the underlying zprint library auto configures whenever you do most anything from the published API, which eventually happened.  But the `:interpose` processing took place prior to the code eventually stumbling into auto configuration.  Thus, the workaround I mentioned simply invoked a configuration step that causes auto configuration from the available files.  The fix, of course, is to explicitly trigger auto configuration in the main program, which I have now done.   It actually took longer to create a test that would successfully notice the missing `:interpose` then to fix the bug.  More than you wanted to know, almost certainly.

It is some small comfort to know that `:interpose` is the only thing affected by this bug.  Because of that, I would like to edit the title of the issue to make that clearer to anyone who is looking for problems if that is all right with you.

Anyway, this will be fixed in release `1.1.2`.

**Comment by mapidentity** [comment]
I'm totally ok with changing the title. Thanks again for investigating, explaining and fixing this issue.

**Comment by kkinnear** [comment]
This is now fixed in `1.1.2`, and you won't need the workaround anymore.  Thanks again for reporting this!

**Comment by mapidentity** [comment]
Can confirm this works, and very happy with it! Should I close this issue?

**Comment by kkinnear** [comment]
I'll close it, thanks!
