### ISSUE TITLE
Enforcing one newline between top level forms

### ISSUE THREAD

**Issue by arichiardi** [kkinnear/zprint#189]
Hi Kim/all,

One of the things we noticed in our workflow is that we end up sometimes with editors/folks adding multiple newlines between forms:

```clojure
(def a :b)


(def c :d)
```

This is rarely something we desire and, while there is an "ignore whitespace" feature, it shows in diffs. In short, we always want:

```clojure
(def a :b)

(def c :d)
```

I was wondering if there is a way to say to `zprint` to "always keep at most one newline between forms. I guess similarly to `:parse {:interpose "\n\n"}` but for file formatting?

I could probably `echo` the file and pass it through `zprint` but the explicit feature/configuration would make the formatting scripts simpler.

Thanks, Andrea

**Comment by kkinnear** [comment]
While I understand what you want, I'm not sure I've got a good handle on the environment (context) in which you want it.

If you use `{:parse {:interpose "\n\n"}}` for a file, you will get one blank line between every top level form, which is what I think you want. 

That said, there is a currently outstanding issue (which is fixed in the upcoming `1.1.2`) which causes a `{:parse {:interpose ...}}` to not configure successfully on the uberjar or pre-built binaries unless you have an options map on the command line.  The command line options map can be empty, that is: `'{}'`, but some options map must appear on the command line to get the `{:parse {:interpose ...}}` to configure successfully if it is in your `~/.zprintrc` or project level `.zprintrc` file.

**Comment by arichiardi** [comment]
Oh yeah that indeed worked. Thanks closing this!
