### ISSUE TITLE
"Consistent" cond formatting

### ISSUE THREAD

**Issue by NoahTheDuke** [kkinnear/zprint#235]
Hey hey! Love the library so much.

Right now, `cond` (and related forms) will start each pair on a newline, attempt to put the `then` expression on the same line, and then place the `then` expression on the next line if it doesn't fit:

```clojure
(cond
  (simple-check) (short-function-call)
  (and (much-more-complicated-check) (an-even-longer-check-that-is-too-long))
  (look-im-on-the-next-line)
  :else (another-short-call))
```

I would like if it, any time _any_ `then` expression is placed on the next line, all `then` expressions are placed on the next lines:

```clojure
(cond
  (simple-check)
  (short-function-call)
  (and (much-more-complicated-check) (an-even-longer-check-that-is-too-long))
  (look-im-on-the-next-line)
  :else
  (another-short-call))
```

Is this possible?

(I really wish clojure hadn't dropped the parentheses around pairs in cond and let and other binding forms lol.)

**Comment by kkinnear** [comment]
Sorry to be slow to respond.  I was away, and then wrapped up with another issue.

For what it is worth, I too think the extra parentheses around pairs in `cond` and `let` were not all that "extra". 

I see what you want, and agree that it is a reasonable approach.  There is no way to configure zprint to do that at present.  

It turns out that zprint more or less does things in "order", so that finding out that the last thing in a `cond` had the second elements of the pair fit on the next line isn't so easy when doing the first pair in the `cond`.  That said, the justification code does something like this, where if everything justifies correctly, it moves on, but if one element of the `cond` doesn't justify correctly, it will re-do the whole `cond` without justification.  I'm thinking that perhaps I could use the same approach to see if all of the pairs fit on the same line, and if they didn't, then (if it was configured to do so), all of the pairs could be done as though all of the second elements didn't fit.  This would be a more attractive an approach if the current code that handles the justification (or not) wasn't so complex and tangled up.  Maybe an opportunity to clean it up?

Anyway, the bottom line is that I see this as a perfectly reasonable request, and will try to implement it soon.  I don't know if I will get it into`1.2.4` or the next release after that, but I'm definitely interested in making it happen.

Thanks for asking!

**Comment by NoahTheDuke** [comment]
That's awesome and very kind of you, thank you!

**Comment by kkinnear** [comment]
This is in `1.2.4`, just out now.  A nice idea, thanks for the suggestion.

From the `CHANGELOG.md`:

There are pairs in functions like `cond`, in maps, and in bindings. When the right hand part of the pair doesn't fit, it "flows" onto the next line.  A new feature is now available to flow all of the right hand pairs onto the next line if any of them flow because they don't fit.  This will certainly make things take more vertical space, but the additional consistency may make the pairs more easily distinguishable. You can enable this in any of the three possible places by setting `:flow-all-if-any? true` in `:pair`, `:map`, or `:binding`.

**Comment by NoahTheDuke** [comment]
That's awesome, thank you for this.
