### ISSUE TITLE
Change in formatting based on length of threading arrow form

### ISSUE THREAD

**Issue by NoahTheDuke** [kkinnear/zprint#237]
Hey Kim! Always a pleasure using zprint. Here's an odd one that doesn't quite feel like a bug, but maybe is.

I have this code (variables and keys changed to match length of original code):
```clojure
(defn create-user
  ([db user-param] (create-user db user-param nil))
  ([db user-param extra]
   (-> (insert-into :users)
       (values
        [(merge {:email (email user-param)
                 :first_name (first-name user-param)
                 :last_name (last-name user-param)
                 :longish_key (or (:user_id user-param) (:_id user-param))
                 :active true}
                (select-keys extra optional-keys))])
       (returning :*)
       (query db)
       (first))))
```

and if I remove the last line (`(first)`), then it is reformatted to:
```clojure
(defn create-user
  ([db user-param] (create-user db user-param nil))
  ([db user-param extra]
   (->
     (insert-into :users)
     (values [(merge {:email (email user-param)
                      :first_name (first-name user-param)
                      :last_name (last-name user-param)
                      :longish_key (or (:user_id user-param) (:_id user-param))
                      :active true}
                     (select-keys extra optional-keys))])
     (returning :*)
     (query db))))
```

I feel like I somewhat understand the greedy algorithm, trying to make everything as wide as possible first before going long, but this perplexes me because the only change is the number of lines inside of the `->` threading macro. Does the algorithm pivot if there are 10 or more lines?

**Comment by kkinnear** [comment]
The algorithm is considerably more complex than you might have imagined.  Originally, it was pretty simple, but over the first few months as I experimented with it, I found plenty of places where the output looked bad.  Sometimes, really bad. The whole point of (at least classic) zprint is to get output that looks "good", as good as it would look if as if I hand formatted it.  So, when I found things that looked bad, I added to the heuristic that drives the formatting engine.  Over the later years, the changes in that area have quieted down, since the results seem to be pretty good.

Some terminology: your first example formatted the `->` with a "hang".  That is to say the first argument of `->` is "hanging" on the same line as the `->`. The second example, the one you are questioning, formatted the `->` with a "flow".  These are my terms, I just had to have something to describe each thing.

The basic formatting algorithm formats things *both* ways, both a hang and a flow (unless there is some reason why one or the other is off the table in that instance).  It then compares them, and using a complicated and totally empirically derived heuristic, decides which is "better".  From this, you might imagine that zprint is potentially very slow.   Indeed it is, because it does this at pretty much every level, for everything.  That said, there are a number of places where zprint decides that it is trying too hard and cuts back to reduce the run-time, and that seems to work well enough.

In the instance we are discussing, one element of the heuristic compares the number of lines in the hang with the number of elements in the hang.  The point of this was to avoid situations where something was over toward the right margin, and when you hang it, it just spews short lines (as those are all that fit) down the page.  Looks terrible.

The specifics of this part of the heuristic are:
```
p-lines: the number of lines in the hang
p-count: the number of elements in the hang
hang-expand: a configuration param in :list, default 2.0

If this is not true (among a *lot* of other things), it won't accept the hang as "better":

                                     (<= (/ (dec p-lines) p-count) hang-expand))
```
In the second of your examples:
```
p-lines: 10
p-count: 4
hang-expand: 2.0
(/ 9 4) > 2.0 => no hang
```
We can demonstrate that this is the limiting factor, by adjusting `:list {:hang-expand 2.3}`:
```
(czprint i237a {:parse-string? true :list {:hang-expand 2.3}})
(defn create-user
  ([db user-param] (create-user db user-param nil))
  ([db user-param extra]
   (-> (insert-into :users)
       (values
         [(merge {:email (email user-param),
                  :first_name (first-name user-param),
                  :last_name (last-name user-param),
                  :longish_key (or (:user_id user-param) (:_id user-param)),
                  :active true}
                 (select-keys extra optional-keys))])
       (returning :*)
       (query db))))
```
If the formatting difference in your two examples is more than wondering "what in the world is going on here?", you could adjust `:hang-expand` at the top level of the `->` function, like so, to get it to format differently for you:
```
(czprint i237a {:parse-string? true :fn-map {"->" [:noarg1-body {:list {:constant-pair? false :hang-expand 2.3} :next-inner-restore [[:list :constant-pair?] [:list :hang-expand]]}]}})
(defn create-user
  ([db user-param] (create-user db user-param nil))
  ([db user-param extra]
   (-> (insert-into :users)
       (values
         [(merge {:email (email user-param),
                  :first_name (first-name user-param),
                  :last_name (last-name user-param),
                  :longish_key (or (:user_id user-param) (:_id user-param)),
                  :active true}
                 (select-keys extra optional-keys))])
       (returning :*)
       (query db))))
```
This will adjust `:hand-expand` for only the top level of the `->` function.  You could make it a bit larger, and probably not be sorry about it.

I hope this explains what is going on in enough detail.

Thanks for asking.  It is always interesting to figure out what is going on with something like this.

**Comment by NoahTheDuke** [comment]
That's very cool, thank you for the in-depth explanation. Pretty cool that this is so granular! I'm glad to know this isn't a bug or some faulty heuristic.
