### ISSUE TITLE
fn* formatting?

### ISSUE THREAD

**Issue by devn** [kkinnear/zprint#238]
clojure's pprint handles the following:

```clojure
(pp/with-pprint-dispatch pp/code-dispatch
  (pp/pprint (read-string "(let [limit 5 original [:a :b :c :d :e]] (map (fn* [p1__38801#] (map (partial nth original) p1__38801#)) (nth (iterate (fn* [p1__38802#] (for [p p1__38802# n (range (inc (count p)))] (concat (take n p) [(count p)] (drop n p)))) [[0]]) (dec limit))))")))
```
and returns
```plaintext
(let [limit 5 original [:a :b :c :d :e]]
  (map
    #(map (partial nth original) %)
    (nth
      (iterate
        #(for
          [p % n (range (inc (count p)))]
          (concat (take n p) [(count p)] (drop n p)))
        [[0]])
      (dec limit))))
```

Is it possible for zprint to print fn* as #()?

**Comment by kkinnear** [comment]
At present, no.  It is an interesting question, though.  Perhaps you could help me understand the use case you have in mind.  That is to say, why do you want this capability?  I certainly agree that the result is easier to read than than the code with the gensyms in it, but how does this problem come up?  I might be able to extend zprint to do this, but I would like to ensure that I'm solving the real problem if I were to do so.  Thanks for asking!

**Comment by devn** [comment]
Thanks for your reply!

To be fair I almost didn't submit this. The situation arises when you `(read-string "#(inc %)")` => `(fn* [p1__3#] (inc p1__3#))`. Since zprint has `parse-string?`, it doesn't seem strictly necessary to support `fn*`, but I figured it was worth asking/noting as a difference against using Clojure's built-in formatter.

If you do decide to add this, there is one edge case to be aware of, which Clojure's code dispatch doesn't handle the `#(%)` case. See: https://clojure.atlassian.net/browse/CLJ-1181

Again, thanks for taking a look.

**Comment by kkinnear** [comment]
Thanks for the additional information.  I think I've figured out how to implement this, though it will require adding some additional complexity to the basic formatting engine to do so.  It isn't a huge amount of work, but it is far from a trivial change.  I'm wondering -- is this something that you would actually use?  Or were you just alerting me to something that was different from `pprint`?  

For what it is worth, I don't know of anyone actually using `pprint` much to format code.  Structures, yes, but it has been years since I gave up trying to coerce `pprint` to do anything nice to my code.  Of course, you are pointing out how code as structure is formatted, but again -- I don't know of anyone really doing that.  If you are using zprint to do code formatting from structures (i.e., not from strings), please let me know.

Obviously, I'm trying to figure out if this is worth the work.  If you would actually use it, I'll give it a shot.  If this is something to keep up with `pprint`, I'll probably pass until someone says they would actually use it.

Thanks!

**Comment by devn** [comment]
It is definitely "keeping up with pprint". I noticed the behavior when migrating some code that used `code-dispatch` to zprint. I agree that as far as formatting goes, the majority of people are going to reach for zprint. Feel free to close or leave it around in case someone finds a more compelling use case for handling the read value of `#()`.

Thanks,
Devin

**Comment by kkinnear** [comment]
If someone cares a lot about this, please re-open this issue.
