### ISSUE TITLE
Meta-base style multi metadata bug

### ISSUE THREAD

**Issue by arichiardi** [kkinnear/zprint#245]
Hi Kim again,
apologies I am trying to keep it tidy but I have found that with this problem with the new `:meta-base` style.

This time I have a minimal repro:

```shell
echo '(def ^:const ^:private port-file-name ".nrepl-port")' | zprint '{:search-config? false :fn-map {"def" [:arg1-body {:style :meta-base}]}}'
(def ^:const ^:private ".nrepl-port")
```

Multiple keys are allowed on the meta as per the Clojure docs, I know this complicates things and I now that style is experimental so no worries about timing, I'll keep testing what you throw out :smile: 

Thanks for working on my issues as always!

**Comment by kkinnear** [comment]
I'm so lost.  I see what you get, and to you it obviously isn't correct.  But I'm trying to learn what you think is correct by looking at examples, and I don't think I've seen any examples from you where the output above was considered wrong and you specified an alternative output.

I'm guessing that it isn't supposed to be all on one line?  Maybe?  But do you want all of the metadata on the same line
as the `def`, or do you want it some other way?  

I'm more than happy to figure out how to make it look the way you want, but I can't do that if I don't know what you want.  Please, please, whenever you say "this isn't what I want", tell me how you would like it to format.  I'm sure it is obvious to you, but it really isn't to me.  If you've already told me what you wanted for `def` that would format on a single line in #224, I apologize.  I just reviewed all of the examples I found there and didn't see anything that seemed to me to bear on this particular issue.

That said, the changes to `:meta-base` I suggested earlier today in #224 are only going to fix that problem (hopefully), it won't do anything for this one.  Since I don't know yet what the problem is here.  Thanks!

**Comment by arichiardi** [comment]
I think this indeed is something that I assumed was clear, so apologies for not even stating the issue.

It seems like the symbol (in the above `port-file-name`) right after the metadata has been removed.

To restate, formatting is good but the output is without `port-file-name `.

I will try the other suggestions and as usual I really really thank you for helping me learning `zprint` and addressing our team issues!

**Comment by kkinnear** [comment]
Well, you aren't wrong. It is certainly obvious, and I have no idea why I didn't see the problem.  Sigh. I think I was looking for a formatting problem, not a missing piece of code.  My sincere apologies!   

I managed to become a participant in the pandemic in late June (having managed to avoid doing so for a good long time), and I guess my brain still isn't completely back in operation.  I'll see what I can do about this rather egregious problem!  

Thank you so much for noticing it and reporting it!

**Comment by kkinnear** [comment]
So, I've fixed the bug that caused the missing element.  I didn't know how multiple `^:stuff` things were parsed. Turns out that the first meta keyword to the left of the actual symbol is parsed into one `:meta` element, then the next meta keyword to the left is parsed into another `:meta` element, and so on.  Nested `:meta` elements.  Never ran into that, and more or less by accident with the normal formatting it works out fine.  Well, at least nothing is lost.

Anyway, having fixed the bug, the question becomes: how do you want it formatted?

From our conversations in #224, I believe that you would like them all on one line, thus:
```
(def ^:const ^:private ^:test ^:lots ^:of ^:meta ^:stuff port-file-name
  ".nrepl-port")
```
And I can do that with a little work, as I have to have a smarter `:option-fn`, where I detect this kind of metadata input.  I have to use some as-yet undocumented features of the `:option-fn`, as well as make some small additions to the undocumented feature (such that you can't actually try it until `1.2.4` ships).

The problem comes up when it doesn't all fit on one line.  In #224 I presented these options:
```
; Version A 

(deftest ^:database-stuff-and-bother
         websocket-diagnostic-and-a-bit-more-that-does-not-fit
  (let [foo (bar "1")] foo))

; Version B is, I suppose, an alternative

(deftest ^:database-stuff-and-bother
  websocket-diagnostic-and-a-bit-more-that-does-not-fit
  (let [foo (bar "1")] foo))
```
You preferred Version B.

Which is nice, but if I'm going to get all of the `^:stuff` things on the same line if it all fits, if it doesn't all fit, you are going to  get this:
```
; I have narrowed the :width to 60 so it doesn't fit

(def ^:const
     ^:private
     ^:test ^:lots ^:of ^:meta ^:stuff port-file-name
  ".nrepl-port")
```
which is certainly sub-optimal.  That is, actually, what it does today by default, but nobody has every complained because nobody has ever probably had it not fit.

My first recommendation would be -- if you see something like that above, where (for you) it doesn't fit with a `:width` of 100, then maybe you should consider using a map?

Alternatively, I could force it to do something like this:
```
(def
  ^:const
  ^:private
  ^:test
  ^:lots
  ^:of
  ^:meta
  ^:stuff
  port-file-name
  ".nrepl-port")
```
I can force that pretty easily.  I don't think you would want that for every time you have `^:stuff` for metadata, but I could force that approach for an arbitrary number of metadata `^:stuff` elements, say more than 4 or something.

I hoped to be able to do this:
```
(def ^:const
     ^:private
     ^:test
     ^:lots
     ^:of
     ^:meta
     ^:stuff
  port-file-name
  ".nrepl-port")
```
But that turns out to be really hard.  I *might* be able to concoct a guide do to that, given I can determine (with a bit of work) how many `^:stuff` elements there are, but I'm thinking that this isn't maybe worth the work given that having enough `^:stuff` elements to not fit on a line is probably vanishingly rare.  

So, I guess my question is  -- do you want it all on the same line if possible, and if it doesn't fit, it is ok if it does something silly like this:
```
; I have narrowed the :width to 60 so it doesn't fit

(def ^:const
     ^:private
     ^:test ^:lots ^:of ^:meta ^:stuff port-file-name
  ".nrepl-port")
```
and can we consider that a "don't do that" sort of signal.  Since that is what it does by default today and nobody has ever complained.  The theory is that, should you see this sort of output, you should put the metadata into a map, and then all of the nice `:style :meta-alt` stuff I've done will take over with that map.

Or would you like me to automatically shift into this:

```
(def
  ^:const
  ^:private
  ^:test
  ^:lots
  ^:of
  ^:meta
  ^:stuff
  port-file-name
  ".nrepl-port")
```
if you have more than some fixed number of `^:stuff` metadata elements.  Maybe 4 or 6 or something?

Or are neither of those acceptable.

I hope this is clear.

Thanks!

**Comment by arichiardi** [comment]
Oh man I thought I answered here, let me try if it is still in my drafts, sorry about that!

**Comment by kkinnear** [comment]
So, `1.2.4` just out now, fixes the bug with the missing element.  I also did the simpler thing above, but if you want the second thing I can do that in an options map.   I moved the current `:meta-alt` `:option-fn` into `optionfn.cljc` because it was getting kind of long for being in the config map.  Anyway, when you tell me what you want, I'll work on doing that.

**Comment by kkinnear** [comment]
If you want me to something additional, please re-open this issue.  Thanks!

**Comment by arichiardi** [comment]
Thanks @kkinnear - I have been behind testing the new features. Will follow up.
