### ISSUE TITLE
Doesn't work w/ Clojure 1.9.0-alpha16 due to clojure.spec ns

### ISSUE THREAD

**Issue by belucid** [kkinnear/zprint#26]
`spec.cljc` pulls in `[clojure.spec :as s]` rather than `[clojure.spec.alpha :as s]` meaning it's no longer compatible with latest Clojure 1.9 and Spec libs.

**Comment by kkinnear** [comment]
Yes, I know. I'm sorry I wasn't clear when I said in the readme that this was the last zprint that would work with 1.9-alpha15.  I should also have said that it won't yet work with 1.9-alpha16.  I wanted to release a last "best" version for 1.9-alpha15 before I released the version that works with 1.9-alpha16, since there is no way to have one version do both.  The compatibility library clojure-future-spec (for use with 1.8) now works with the new clojure.spec.alpha approach, so I'll be releasing a new version which runs with both 1.9-alpha16 and 1.8 soon, certainly by early next week (and possibly by tonight).

Thanks for letting me know that you care, as I was intending to include some new development with the next release that works with 1.9-alpha16, which would have pushed that release out by days to weeks.  Instead I'll release the 1.9-alpha16 version with the same code as last night's release and do the new development after that.

**Comment by belucid** [comment]
Awesome! Sounds like a great plan. Thank you.

**Comment by kkinnear** [comment]
Just released `zprint 0.4.0`.  This uses `clojure.spec.alpha`, and should work with 1.9-alpha16.  Give it a try!

**Comment by belucid** [comment]
Works like a charm! Thanks @kkinnear !
