### ISSUE TITLE
Backtranslate inline anonymous function reader macro

### ISSUE THREAD

**Issue by riotrah** [kkinnear/zprint#268]
Hey there. Thanks again for this.

Similar to #121 , and _almost_ implemented by its solution, I've observed - whilst using zprint as a library - that fn forms written with `#( ... % ... )` syntax get rewritten always as `(fn* [] ...)`.
I'm not sure if this is some fundamental limitation or anything, but I do know that the existing reader-macro backtranslation feature does not work for it (it doesn't even match `{:fn-map {"fnc*" ...`). 

I would imagine that even if it did match, the `[]` arg vec might appear as the first list item anyways.

Is this doable?

**Comment by kkinnear** [comment]
Thanks for the reference to #121, as I agree -- this is kind of related. 

 I can reproduce something that I *think* is what you are experiencing, and it looks pretty bad.  But I'm not positive it is actually what you are experiencing.

It would help me if you could give me a concrete example of how you are using zprint and the results you are getting that you don't like -- for two reasons.  First, it would make sure that when I do something to fix this, as I hope to do, it actually fixes your problem instead of maybe just the way I've contrived to generate what looks like a similar problem.  Second, it would give me a little insight into your use case, which would help me to know if I have other related problems and possibly need a more general solution.  Thanks!

**Comment by kkinnear** [comment]
Yes, this is going to be a real challenge.  I have prototyped something that could sort of work, but it also leaves things associated with another namespace qualified by that namespace, which looks different than I expect you would want.  I'm very interested in how you are using zprint and what you get now and, particularly what you would like to see when this issue is resolved (which I may not have mentioned above).   Thanks.

**Comment by riotrah** [comment]
**I must apologize for wasting your time and leading you down a wild goose chase.** 

I learned after trying out various ideas that it is _not_ `zprint` "at fault", but rather a lack of understanding on my part of how clojure code is read. 

---

If you're curious, I was trying to take arbitrary function definitions as part of a `defn-like` macro, which would format and prett-ify those fn's sources as string, to be rendered on a webpage. Eg, as code sample snippets for other devs. It just looked weird that source that was written with `#(` turned into `(fn* ...`.

No matter how I print or format it, it will do that translation. Maybe it's because the way I'm trying to acquire the source is suboptimal, but I'm not sure how else to beyond using the forms directly within the macro (or via `&forms`).

I didn't know this, nor could I find good documentation on this (unfortunately, googling for _"Clojure "fn*" macroexpand anonymous function #()"_ etc doesn't provide anything useful now that google doesn't do _exact_ matches anymore).

---

That being said, if it were trivial for zprint to still do my suggested reader macro back-translation, that would be awesome, but certainly not worth spending more of your time on. If you're satisfied, feel free to close as you've certainly done enough digging <3

**Comment by kkinnear** [comment]
Thanks for the explanation.  It isn't trivial for zprint to do the back translation, but I've just about finished it up.  I've even gotten the tests already written!  I have a few things to refactor and some documentation to do, but I think it will do what you want.  I'm gong to go ahead and finish and release it.  It is actually implemented using a new more general capability to rewrite structures in arbitrary ways, so maybe that will be useful for some other situation in the future in addition to making  this possible.  It should be in `1.2.5`, coming soon-ish.  It will be a new style `:anon-fn`.  Unless I find a better name for it, which would probably be a good idea, now that I think on it.

**Comment by riotrah** [comment]
Incredible. Lookin forward to testing it out. Thanks for jumping into action in any case! The addition of this feature would then make the argument of "why not just use pprint instead of an additional dep" all the less compelling 😉

**Comment by kkinnear** [comment]
This is in `1.2.5`, and it is still called `:style :anon-fn`.  I hope it does what you want.

**Comment by riotrah** [comment]
Thanks so much @kkinnear !!!!
