### ISSUE TITLE
Keep unchanged kondo directives

### ISSUE THREAD

**Issue by dpom** [kkinnear/zprint#303]
Thank you for zprint. It is a very good and versatile formatter.

At the moment, I'm using the `:respect-bl` style. I have an issue with the kondo directives that zprint turns from:
``` clojure
#_{:clj-kondo/ignore [:unresolved-symbol]}
```
to
``` clojure
#_#:clj-kondo{:ignore [:unresolved-symbol]}
```
What option should I use to prevent this conversion?

**Comment by kkinnear** [comment]
Thanks for asking!  Unfortunately, I'm having trouble reproducing the problem you show above.  When I try it, I get:
```
zprint.core=> i303
"#_{:clj-kondo/ignore [:unresolved-symbol]}\n"
zprint.core=> (czprint i303 {:parse-string? true})
#_{:clj-kondo/ignore [:unresolved-symbol]}
```
which is kind of what you (and I) would want.  

I don't know where the additional '#' is coming from.  If you could also provide whatever you have in your `~/.zprintrc` or `.zprintrc` or `.zprint.edn`, it would probably help me reproduce this problem.   The most likely situation is that something that you have configured for zprint is causing this problem, so if you give me your configuration I will be more able to fix this problem.  

Thanks!

**Comment by kkinnear** [comment]
Just FYI, I highly edited the my original reply, and in the event you are looking only at the email, I think that edits don't show up in the email.  I can reproduce this, but in order to give you the support that will help, I need a little additional information (which you can see in the edited response to your original posting).  Thanks.
