### ISSUE TITLE
Inline comments always get moved to new lines

### ISSUE THREAD

**Issue by AdamFrey** [kkinnear/zprint#33]
As far as I can tell, inline comments always get moved to a new line.

```
{:a 1 ; Inline comment about :a 1
 :b 2}
``` 
becomes
```
{:a 1
 ; Inline comment about :a 1
 :b 2}
```
Which was quite surprising to me. I am nowhere near the 80 char wrap limit. I tried setting `{:comment {:wrap? false}}` to avoid the comment being moved but the behavior for inline comments is unchanged.

I am using `zprint-filter-0.4.3` which is where I observe this behavior.

**Comment by kkinnear** [comment]
You are quite correct, inline comments are treated the same way full line comments are treated, and so they always go on a new line.  This is a result of zprint completely ignoring the current spacing and line contents, and just doing the best it can to come up with a good looking format for the code. Zprint doesn't just indent what you've already done, it formats it from scratch.  It actually can't tell inline comments from regular comments, and so treats all comments the same.

This is in part because my experience is that people don't use inline comments that much in Clojure, though I certainly grew up programming with an inline comment on just about every line.  But people seem to be pretty frugal with comments these days, and as I look at my code and lot of others, I don't see a lot of inline comments.  I think that is also in part because the right "edge" of the code isn't particularly distinguished, and so several inline comments rarely would line up with each other, so they just look kind of bad.

All that said, now that the basic formatting is working, I would consider trying to better handle inline comments if that is important to you.  Where better handle would be actually remember which comments are inline, and try to print them on the same line.

**Comment by kkinnear** [comment]
I want to thank you for pointing this out.  I had pretty much written off inline comments as a combination of unnecessary and kind of "not what zprint does", but because you brought this up, I spent some time thinking about how I could implement support for them.  And then to do it.  I have managed to implement support for inline comments (due in part to some unobstructed time on a transcontinental plane flight), and they will be available in zprint 0.4.4.  It will be a few days before I have time to release this version, but I expect to do so sometime in the next week.

This initial support will simply keep the inline comment on the same line it was originally, and wrap it if necessary.  It keeps the original spacing from the code on that line to the start of the comment.  

While I've tested it with plenty of concocted examples, I would be interested in getting some real Clojure code that has inline comments.  If you have some that you could share, that would be great, although I certainly understand if you don't have things that you can share.

I'm interested in some "real" code, since I have some ideas about how to make the inline comments look better by working on the left alignment of inline comments in groups.  Which is an interesting technical challenge.   I also would like to just check to ensure that my implementation works successfully, since the real world is always more interesting than my imagination.

I appreciate that you gave me a push to consider how to implement inline comments, which caused me to realize that there is a phase of the formatting process where I could implement some useful processing.  I expect that there will be some other things that I can do at this phase.

I also realized that I have trained myself to not use inline comments because they didn't work. 
 I've started to use them (sparingly) again.  So, thanks again for asking!

**Comment by AdamFrey** [comment]
Wow, thanks for you work on this. I don't have any code with inline comments right now that isn't closed source, unfortunately.

You probably are familiar with clojure-mode on emacs which by default pushes inline comments that start with only one semicolon out to column 40, but also left-aligns inline comments on subsequent lines on whichever line is the farthest out column, like:
```
(def a "some-long-value...") ; inline comment 1
(def b "shorter")            ; inline comment 2 
```
I don't know how feasible that would be to implement in zprint, but I think it does make a nice, readable table of code and comments

**Comment by kkinnear** [comment]
I'm going to release the basic support I described above in zprint 0.4.4, since I don't know how long it will be before I have something more sophisticated for alignment of inline comments. At least they will work.

I'm actually not familiar with clojure-mode on emacs.  For a variety of reasons, including a distressing tendency to play with my tools instead of using them, I use a vi-clone that, other than syntax coloring, has little lisp support.  So I'm always interested in hearing about how other tools format Clojure.

Regarding emacs, are you saying that it will put a contiguous group of inline comments at column 40 if they all can start there, but if they can't all start at 40, it will shift the entire group to some distance (? distance) beyond the rightmost bit of code that sticks right beyond 40?  Presumably, one line without an inline comment breaks the contiguity of the group and starts a new group?

Thanks for the information, I really appreciate it!

**Comment by kkinnear** [comment]
I'm going to close this issue, as I consider this bug "fixed", and open an enhancement for aligning the inline comments.  But feel free to continue to add to this issue, or the new one.
