### ISSUE TITLE
zprint-file-str doesn't take options

### ISSUE THREAD

**Issue by kommen** [kkinnear/zprint#40]
`zprint-file-str` only takes the string to reformat and the specifier.
This seems inconsistent to me, especially because in the readme it is stated:

> `;; All zprint- functions also allow the following arguments:`
>`(zprint x <options>)`

I use `set-options!` now, which works. But I was wondering if this is intentional or not.

**Comment by kkinnear** [comment]
Well, yes, this _is_ inconsistent.  `zprint-file-str` was an internal capability that I decided to expose in the readme because it seemed like there might be people who would use it, but unfortunately I didn't think at the time to regularize its arguments.  Given it is already out there the way it is, it seems unfriendly to change the arguments at this point despite the inconsistency.  I can change the readme to say "Most zprint- functions ...".  But I don't expect that is the real issue.

I presume that you would find `zprint-file-str` more useful if it took an options map in its call, instead of requiring you to use `set-options!`.  Given a quick look, I think that I could add an options map as an optional third argument for `zprint-file-str`, which might give you what you want without breaking anyone else who is using it.   I'm not positive that will work out (largely because the options would have to take precedence over any others), but I think it will.  Seems like that would make `zprint-file-str` more useful for everyone, even if a bit inconsistent.  Would that be useful for you?

**Comment by kommen** [comment]
Thanks for the detailed explanation!

I think I don't fully understand:

> I'm not positive that will work out (largely because the options would have to take precedence over any others), but I think it will.

How would this behave different than the other `zprint-` functions regarding options precedence?

As mentioned, I can already do what I want, so no api change needed from my side – I was just curios.

**Comment by kkinnear** [comment]
zprint-file-str now takes an options map in 0.4.6.
