### ISSUE TITLE
Vector wrapping when it contains lists

### ISSUE THREAD

**Issue by kommen** [kkinnear/zprint#42]
This code (generating hiccup data):

```clojure
(defn main [{:keys [current-person] :as view-data} & hs]
  (page/html5
   (head view-data)
   [:body
    (if (some? current-person)
      (navbar-logged-in view-data)
      (navbar-logged-out view-data))
    (flashes view-data)
    hs
    (bugsnag view-data)
    (scripts view-data)
    (start-app-script (:server.system/profile view-data))]))
```

is formatted to this (default and community styles):

```clojure
(defn main
  [{:keys [current-person], :as view-data} & hs]
  (page/html5 (head view-data)
              [:body
               (if (some? current-person)
                 (navbar-logged-in view-data)
                 (navbar-logged-out view-data)) (flashes view-data) hs
               (bugsnag view-data) (scripts view-data)
               (start-app-script (:server.system/profile view-data))]))
```

This is very unreadable, especially because of the `(flashes view-data) hs` wrapped into the same line as the `else` branch of the `if`.

Setting `{:vector {:wrap-coll? nil}` fixes this, but I was wondering if the default formatting is intended as shown above, since I find this unreadable.

**Comment by kkinnear** [comment]
Good question!  The default formatting is intended to be `:wrap-coll? true` in part because I have some very complex argument vectors with a lot of destructuring in them.  They come out pretty much like you would format them by hand if you use `:wrap-coll? true`, but kind of spew down the page if you use `:wrap-coll? false`.  Generally, I find vectors to be ok with `:wrap-coll? true`, though I certainly agree that your example is terrible.  I have recently also found some other situations where people are using hiccup-like vectors which come out looking pretty unlovely after going through zprint.  

In the short term, you could use `{:vector {:wrap-coll? false} :fn-map {"html5" :flow "defn" :arg2} :style :community}` to get zprint to format the example exactly as you did.  If you like that, you could put that in your `~/.zprintrc` file, and then it would work whether you were using lein-zprint or the zprint-filter or whatever.  But you probably already know that.

I'm not wild about making `:wrap-coll? false` the default, as you appear to be suggesting.  But I'm thinking about how to get vectors with hiccup-like data to format better.  I'm thinking of adding some configuration to `:vector` which would be a map of possible first things in a vector, each of which would be associated with an options map to merge in before formatting the vector.   In the case you have brought up, you would specify something like 
```clojure
:vector {:format-type {:body {:vector {:wrap-coll? false}}}}
```
in your ~/.zprintrc to get the formatting you want for your hiccup vector. 

The question for you is: would keying off of the first thing in the vector work in your context?  Are there few enough first things in vectors that you could specify the formatting for all of them you want?  Would it work if they had to all be constants, like keywords, strings, or numbers?

Thanks for bring this up!

**Comment by kommen** [comment]
Thank's for the explanation!

Unfortunately I think neither `{:vector {:wrap-coll? false} :fn-map {"html5" :flow "defn" :arg2} :style :community}` nor `:vector {:format-type {:body {:vector {:wrap-coll? false}}}}` would be sufficient for us. For our affected functions the hiccup vectors can not be pinned down to a few function calls or keywords (like `:body` in this example) as the first element.

But the number of functions affected by this is very small (and the one posted above is actually the only really terrible), so I think we can do by using the `;!zprint` special comments for either the few functions or for the whole file.

> The question for you is: would keying off of the first thing in the vector work in your context? Are there few enough first things in vectors that you could specify the formatting for all of them you want? Would it work if they had to all be constants, like keywords, strings, or numbers?

So keying by the first thing's name probably wouldn't work well, since we use hiccup's ability to specify css classes for elements as the first keyword in the vector a lot (e.g `:div.foo.bar`).But the vectors do have a keyword as their first element in most cases, so to differentiate by first thing's type might be a way.

**Comment by kkinnear** [comment]
First, maybe I wasn't clear.  This: `{:vector {:wrap-coll? false} :fn-map {"html5" :flow "defn" :arg2} :style :community}` should work for you right now.  It formats at least the example you gave me exactly like you formatted it, and doesn't require any new features or recognition of what is in your vectors to operate.

Second, thanks for the information about the content of your vectors.  Given that, I'm thinking that I might just allow people to specify a one argument function, to which I'd pass the first expression in the vector, and if it returned a non-nil value, zprint would assume it was an options map and merge that into the currently executing options.  This would provide full generality at little cost if you didn't use it.  If you wanted to do regular expressions in the function (at some performance cost, I would expect), you would be free to do so.  The only restriction would be that you would have to make a decision as to what options map to return (if any) based on the first expression in the vector.

I can already think of other uses for this.  If this catches on, I could see providing a later capability which would give you the whole vector instead of just the first part of it, and you would return either nil or a vector containing the vector to print and the options map to use to print it with.  That works well for structures, but less well for code, because you would lose the comments in the transition to structure.

So, I need to think about this a bit more, but at least the first approach (using the first element of the vector to make a decision) would work for code or run-time structures equally well.

**Comment by kommen** [comment]
Sorry, I was not clear: I figured that I could use the `fn-map` today, but we're totally fine with what zprint produces with just `{:vector {:wrap-coll? false}`.

**Comment by kkinnear** [comment]
In trying out the examples in `rum`, I found the `defc` and `defcc` code to look good, now, but the rum HTML data looked terrible.  So I implemented `{:vector {:respect-nl? true}}` which will respect newlines in vectors where this is set.  But since vectors show up in lots of places (e.g., argument lists), that isn't always good.  So I also implemented `{:vector {:option-fn-first #(...)}}` which will allow you to define a two argument function which will be given the first element of a vector and will output either `nil`, which means do nothing, or an options map which will be used for the rest of the formatting for this vector.  There is also a new style `{:style :keyword-respect-nl}` which will respect  existing newlines in all vectors whose first element is a keyword, which I think will cover most hiccup and rum HTML vectors.  (It is implemented with `:respect-nl?` and `:option-fn-first`.)  All of this is documented in the readme (as I know I didn't tell you enough to actually use it, above).  Given all of this, the rum examples look pretty good now, and your rum HTML code should look good too if you hand-format it and tell zprint `{:style :keyword-respect-nl}`.

This is all in 0.4.6.
