### ISSUE TITLE
Community styles for cond->

### ISSUE THREAD

**Issue by kommen** [kkinnear/zprint#49]
In the default styles, `cond->` is formatted with `:arg1-pair-body` https://github.com/kkinnear/zprint/blob/ccfc04f1af44546095326e4e4d1acce641bffede/src/zprint/config.cljc#L295, in the `:community` styles `:none-body` https://github.com/kkinnear/zprint/blob/ccfc04f1af44546095326e4e4d1acce641bffede/src/zprint/config.cljc#L526 is used.

According to the style-guide (https://github.com/bbatsov/clojure-style-guide#body-indentation), I think `:arg1-pair-body` would be more appropriate for the `:community` styles as well.

Not a big deal, since we can just revert it back to the default setting, but wanted to ask for the intention here.

**Comment by kkinnear** [comment]
First, I'm always interested in any suggestions about the community style, since I don't use it.  So thanks for getting in touch about this.  

Regarding this particular issue, I made `cond->` `:none-body` since the part of the community standards that you reference certainly suggested that it needed `body` indentation.  Leaving off the `:arg1-pair` part seemed like I was removing my personal approach to how it should look, and looking over the standards I don't see any `cond->` in it at all.  Yet `condp` and `case` seem like they are close to `cond->`, and `case` in particular is shown as `:arg1-pair-body`.  So I can't reconstruct what made me change the formatting for `cond->` in the community style.  I'll remove that change and leave it as `:arg1-pair-body`.  Thanks for bringing it up!

**Comment by kkinnear** [comment]
Available in 0.4.8.
