### ISSUE TITLE
shadow-cljs complains about `:gen-class`

### ISSUE THREAD

**Issue by colindresj** [kkinnear/zprint#51]
I'm using shadow-cljs to compile my Clojurescript and it complains (loudly) about the ns form of `main.cljc`. I believe it's because `gen-class` isn't implemented in Clojurescript. Wrapping the `(:gen-class)` expression in a `:clj` reader conditional fixes it for me. Happy to put together a PR.

**Comment by kkinnear** [comment]
Thanks for reporting this.  Embarrassingly enough, I actually have used shadow-cljs a bit doing some performance testing with node, and saw this problem go by on the screen, but as it didn't seem to affect the results, I didn't dig into it.  In part because I know almost nothing about shadow-cljs, so I wasn't sure what to expect as I was using someone else's shadow-cljs setup.  But now that you have pointed out the problem (and the fix), it looks much better.  I still get:

```
[:script] Compiling ...
------ WARNING #1 --------------------------------------------------------------
 File: zprint/core.cljc:389:1

 unreachable code
--------------------------------------------------------------------------------

nil
[:script] Build completed. (80 files, 11 compiled, 0 warnings, 30.68s)
```
which in my current code points to something with `#_` on the front, so I don't quite know what to make of that. Also, the "0 warnings" is interesting. Otherwise, it seems to be much cleaner.

I'll release this in 0.4.8, which should be out in a week or two.  Thanks again for pointing out the problem and the solution!

**Comment by colindresj** [comment]
No problem. Happy to help out
