### ISSUE TITLE
Graal Binary Compilation

### ISSUE THREAD

**Issue by zerg000000** [kkinnear/zprint#52]
It would be interesting to have this feature and the effort is not very high

https://gitlab.com/konrad.mrozek/cljfmt-graalvm/

**Comment by kkinnear** [comment]
Yes, I saw that too, but when I looked earlier, the instruction for how to do this weren't in his readme.  I'll give it a try soon.

It will be interesting to see how it stacks up with the "app-cds" version of the [zprint-filter](https://github.com/kkinnear/zprint/blob/master/doc/filter.md), which starts up and runs pretty fast already, using the app-cds feature of the JVM.

I'll let you know when I've got something to share.

**Comment by kkinnear** [comment]
I'm not ready to release anything yet, but the early results are impressive.  

It builds with  "UnsupportedFeatureExceptions" , but if I tell it to "tell me about these problems at runtime", I don't get any at runtime.  So, for now, I'm going to test it as though it didn't build with "UnsupportedFeatureExceptions".

On MacOS, zprint with graalvm starts up in about 1/2 the time as zprint with node.js when the file system cache is cold.  After the file system cache is hot, the node.js zprint start time is 1/2 of what it was with a cold cache, and the graalvm zprint starts up in 1/10 the time as node.js zprint.   

Regarding run time, the graalvm zprint takes about 60% of the time to format a long file as the JVM zprint-filter takes and about 17% of the time it takes the node.js zprint for the same file.

So, on MacOS, the graalvm zprint is much faster to start than the node.js zprint, and runs considerably faster than the JVM zprint, so it wins in both areas.

I will work on releasing a version of this for MacOS.  Linux is going to be a bit of a challenge, but I'll see about that.  That, of course, is the rub here -- we are back to "build a different version for eash system".

**Comment by zerg000000** [comment]
The speed improvement is impressive! But it make deployment dumb again (build binary for each os, especially, windows are not yet supported). cannot wait to see a blaze fast zprint with emacs!

**Comment by kkinnear** [comment]
A few questions for you, if you don't mind:

What OS do you run on?  Linux, MacOS, Windows?  if Linux, which version?  Since you asked for this, I want to make sure that I create a version that will be useful for you if at all possible.

You sound like an emacs user.  Have you been using zprint-filter-0.4.7 (or any version) with emacs already?  I ask, because in the example GitHub repo that you referenced, there was some code for cljfmt to integrate it into emacs.  It looks like cljfmt takes a filename and reformats (well, indents) it "in place".  Where zprint-filter-x.y.z operates as a "filter", reading from stdin and writing to stdout. 

So I'm wondering if the filter approach integrates with emacs well, or if I should be exploring changing it to accept a filename.  Currently the zprint-filter takes an options map as its only argument, but I expect I could extend it to so that, if given a switch and a filename, it would reformat that file in-place, and absent a file switch it would still operate as a filter.   

Do you have any insight on this?

**Comment by kkinnear** [comment]
Available in 0.4.8!
