### ISSUE TITLE
Enable :nl-separator? for hangs

### ISSUE THREAD

**Issue by agriffis** [kkinnear/zprint#55]
I'd like to use this style:

```clojure
(cond x
      y

      a
      b

      :else
      c)
```

As I understand it, `:nl-separator?` only kicks in for flow instead of hang. Are you opposed to enabling it for hangs?

**Comment by kkinnear** [comment]
Interesting request!  I'm not at all opposed to having it work for hangs, though I suspect that there was a reason I didn't allow that (as I tend to allow pretty much anything that works, as I'm sure you have noticed).  I'll give it a look and figure out if I can make this work for you.

**Comment by kkinnear** [comment]
This is already possible! Here is how you can do it:
```clojure
(czprint "(cond x y a b :else c)" {:parse-string? true :pair {:flow? true :indent 0 :nl-separator? true}}) 

(cond x
      y

      a
      b

      :else
      c)
```
You might think that `y` was a hang, but actually, it isn't.  Though that escaped me too, when I first looked at your request.  This would be a hang for `y`:
```clojure
(cond x y
```
So, since `y` is a flow, then `:nl-separator?` works fine.  

Whether or not the entire set of pairs is in a hang or a flow relationship with the `cond` is independent of the hang or flow relationship of the right hand element of each pair.  The `:pair-fn` configuration option controls whether or not zprint tries to hang the entire set of pairs for the `cond` or not.  Here we tell it not to:
```clojure
(czprint "(cond x y a b :else c)" {:parse-string? true :pair {:flow? true :indent 0 :nl-separator? true} :pair-fn {:hang? false}}) 
(cond
  x
  y

  a
  b

  :else
  c)
```
Like all hangs, if hanging the `:pair-fn` arguments pairs is longer than flowing them, it will flow them on its own.  You'll still get the blank line from the `:nl-separator?` in that case.  For example:
```clojure
; width 30
(czprint "(cond xxxxxxxxxxxxxxxxx yyyyyyyyyyyyyyy aaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbb :else ccccccccccccccccc)" 30 {:parse-string? true :pair {:flow? true :indent 0 :nl-separator? true}}) 
(cond xxxxxxxxxxxxxxxxx
      yyyyyyyyyyyyyyy

      aaaaaaaaaaaaa
      bbbbbbbbbbbbbbbbbbbbbb

      :else
      ccccccccccccccccc)
nil

; width 20
(czprint "(cond xxxxxxxxxxxxxxxxx yyyyyyyyyyyyyyy aaaaaaaaaaaaa bbbbbbbbbbbbbbbbbbbbbb :else ccccccccccccccccc)" 20 {:parse-string? true :pair {:flow? true :indent 0 :nl-separator? true}}) 
(cond
  xxxxxxxxxxxxxxxxx
  yyyyyyyyyyyyyyy

  aaaaaaaaaaaaa
  bbbbbbbbbbbbbbbbbbbbbb

  :else
  ccccccccccccccccc)
nil
```
I hope this helps!  Thanks for asking.  Much of this is far from obvious.

**Comment by agriffis** [comment]
Thanks @kkinnear! I had to read through this and the documentation a few times to understand the relationship between `:pair-fn` and `:pair` but it's making sense now. Your explanation (and doc) is great--it's just a complex thing to wrap my brain around :-)
