### ISSUE TITLE
Qualified symbols/keywords

### ISSUE THREAD

**Issue by foobar27** [kkinnear/zprint#62]
Hi,

I'm looking for a flexible solution to pretty-print code generated by macros, and zprint does a pretty good job. However, when I execute it on syntax-quoted forms, the output is cluttered by namespace qualifications for keywords and symbols (lifting namespaces does not really help here).

```clojure
(zp/zprint-str `(defn foo# [x#] (str x# 42 ::x)))
;; =>
(clojure.core/defn foo__16150__auto__
  [x__16151__auto__]
  (clojure.core/str x__16151__auto__ 42 :user/x))
```

I would like to have an output similar to:
```clojure
(defn foo__16150__auto__
  [x__16151__auto__]
  (str x__16151__auto__ 42 ::x))
```

I tried to implement the translation of the symbols I wish:
https://gist.github.com/foobar27/d313c2f4a35af8f2125dacde54a8d3ca

But unfortunately it isn't that simple. 
* It requires good code walking (think ztellman/riddley) to avoid accidental name-clashes. For example, it would be dangerous to replace `clojure-core/map` with its unqualified counterpart `map` in the following snippet:
```clojure
(clojure.core/let [map 42] (clojure.core/map clojure.core/identity [1 2 3))
```
* Furthermore, a `(ns ...)` declaration, or a `(require...)` in the middle of the code might completely change the mappings.

Luckily both situations are quite rare in "good" macros, so I could live with a solution which ignores the two problems (my current solution is a regex replace...).

Would all this be in the scope of zprint? If not, do you recommend a way how I could build it on top of zprint? For example I could:
* implement a hook which is called when zprint renders a keyword/symbol.
* attach meta-data like :zprint.core/string-representation to forms, which would by-pass the zprintf rendering of the annotated forms.

What do you think?

Thanks

Sébastien

**Comment by kkinnear** [comment]
I'm quite willing to extend zprint to allow you to do what you want, though I don't see zprint itself making judgements about which things should be namespace qualified and which should not.  That is to say that a general solution to that problem seems like something I don't wish to take on and maintain.

Of the two extensions to allow you to get what you want that you mention, the meta-data one is probably the more straightforward to implement in zprint, but I don't see how it gets you very far.  Do you really expect to attach meta-data to each symbol you want rendered in a non-standard way?  That means that you need to walk the structure yourself before calling zprint.  Which I guess you could do.  I don't like this, though I can't quite find the right metaphor to describe why.

The other approach, calling a hook when printing a symbol, seems easier from the user standpoint, as you don't have to wander around the structure on your own before calling zprint.  Certainly that's going to lower your performance, but I don't expect that whatever you are formatting is very big so you probably don't care too much.  I already have one hook for formatting vectors, though the hook returns an options map, not a string.

I could imagine a hook for symbols which would pass in the current options map and a symbol and the current string planned for that symbol, and accept a string to render that symbol as the return.  Seems like that would be the easiest thing for you (or any other user) to integrate with.  I need to think a bit how that translates to the source code formatting situation (if at all).  But it seems straightforward.

Two questions:

1. Do I seem be understanding your use case?
2. Does the hook before printing a symbol sound like the best from your standpoint, as a user of zprint?

**Comment by foobar27** [comment]
Thanks for the quick response.
I gave it another try and managed to solve the problem without any changes on zprint, rewriting the symbols and keywords as needed:
https://github.com/foobar27/code-pprint/blob/caf0897641589d247d9366927421fe87eae54c47/src/code_pprint/core.clj#L54
Not sure yet if I like the solution, since it relies on the fact that `(str (keyword  ":a"))` evaluates to `"::a"` (but I guess the given keyword is different than the one interned by `::a`).
But it solves the problem, especially since I only need it for debugging purposes. 

The other drawback is that it does complete macro-expansion. That seems to be the price you have to pay to be able to correctly introspect scopes. I might implement another solution which uses naive code walking (no macro expansion), which would be more intuitive, but less correct (a name clash could be introduced by some non-hygenic macro call). 

I guess there is no easy and correct solution for the problem. 

I will close the ticket, and in case somebody sees more clear into the issue he/she can re-open it.
