### ISSUE TITLE
Feature: Elastic tabstops

### ISSUE THREAD

**Issue by dijonkitchen** [kkinnear/zprint#64]
Can zprint utilize [elastic tabstops](http://nickgravgaard.com/elastic-tabstops/)?

**Comment by kkinnear** [comment]
Not having ever heard of "elastic tabstops", I followed the link, read about them, and downloaded the "elastic notepad".  All of this is interesting, but I'm not sure what you are looking for zprint to actually _**do**_.  That is to say, what do you mean by "utilize"?  zprint works hard to get the indentation right for a monospaced font.  It could certainly output tabs instead of 2 character spaced indents, but sometimes the indent is way across the page.  Frequently it isn't associated with any other tabstops -- a "hang" is just something placed below something else with a lot of space in front of it.  Perhaps every space between things becomes a tab?  Not clear.

If all you are asking is "Does zprint support elastic tabstops now?", the answer is no.  If you are asking "Could zprint be made to support elastic tabstops?", then I need more information.

At this point, I would need to see a better description of what you want in order to decide if zprint can be made to do it in a reasonable way.  I'm asking you to show me some Clojure code and where you would put the elastic tabstops to get what you want.  If that is even what you want.  

Once I undersand that, before I were to dive in to implementing elastic tabstop support in zprint, I would also need to understand a reasonably compelling use case.  It is entirely possible that you could enthuse me to do this work.  That said, I don't yet even understand what work needs to be done.

**Comment by dijonkitchen** [comment]
Thanks for taking the time to look at this @kkinnear! 

I don't think it's a tabs versus spaces thing since that's where soft tabs comes in. My question is really about if zprint could support elastic tabstops. 

Here's an example of what I mean: https://github.com/clojure-emacs/clojure-mode#vertical-alignment

By doing this kind of formatting across different data structures, it'll make the code more readable. As a data point, Golang uses it as their standard formatter for the language via https://golang.org/pkg/text/tabwriter/ .

**Comment by kkinnear** [comment]
If your question is: "Can zprint output code like the vertical alignment in the first link?", then the answer is yes.

First, will zprint do it for code? (Which is why I'm doing this as a string):
```clojure
zprint.core=> (def issue "(def my-map {:a-key 1 :other-key 2})")  
#'zprint.core/issue
zprint.core=> (zprint issue 20 {:parse-string? true})
(def my-map
  {:a-key 1,
   :other-key 2})
nil
zprint.core=> (zprint issue 20 {:parse-string? true :style :justified})
(def my-map
  {:a-key     1,
   :other-key 2})
nil
```
Second, can zprint do it for a map at the repl?
```clojure
zprint.core=> my-map
{:a-key 1, :other-key 2}
zprint.core=> (zprint my-map 20)
{:a-key 1,
 :other-key 2}
nil
zprint.core=> (zprint my-map 20 {:style :justified})
{:a-key     1,
 :other-key 2}
```
In both case, the answer is yes.  I called this "jusitify" instead of "vertical alignment".  This is available individually for binding pairs, maps, and pair-fn's (mostly cond variants).  The `:justified` style is defined as:
```clojure
    :justified {:binding {:justify? true},
                :map {:justify? true},
                :pair {:justify? true}}
```
You can see this in more detail if you do `(czprint nil :explain)`.

Some code looks better justified, some doesn't.  A particularly striking example is the definition of `defn`  Look at the big `let` form in the middle.  
```clojure
zprint.core=> (czprint-fn defn)
(def
  ^{:doc
      "Same as (def name (fn [params* ] exprs*)) or (def
    name (fn ([params* ] exprs*)+)) with any doc-string or attrs added
    to the var metadata. prepost-map defines a map with optional keys
    :pre and :post that contain collections of pre or post conditions.

  Spec:
    args: (cat :fn-name simple-symbol?
               :docstring (? string?)
               :meta (? map?)
               :fn-tail
                 (alt :arity-1 :clojure.core.specs.alpha/params+body
                      :arity-n
                        (cat :bodies
                               (+ (spec :clojure.core.specs.alpha/params+body))
                             :attr-map (? map?))))
    ret: any?",
    :arglists '([name doc-string? attr-map? [params*] prepost-map? body]
                [name doc-string? attr-map? ([params*] prepost-map? body) +
                 attr-map?]),
    :added "1.0"}
  defn
  (fn defn [&form &env name & fdecl]
    ;; Note: Cannot delegate this check to def because of the call to (with-meta
    ;; name ..)
    (if (instance? clojure.lang.Symbol name)
      nil
      (throw (IllegalArgumentException.
               "First argument to defn must be a symbol")))
    (let [m (if (string? (first fdecl)) {:doc (first fdecl)} {})
          fdecl (if (string? (first fdecl)) (next fdecl) fdecl)
          m (if (map? (first fdecl)) (conj m (first fdecl)) m)
          fdecl (if (map? (first fdecl)) (next fdecl) fdecl)
          fdecl (if (vector? (first fdecl)) (list fdecl) fdecl)
          m (if (map? (last fdecl)) (conj m (last fdecl)) m)
          fdecl (if (map? (last fdecl)) (butlast fdecl) fdecl)
          m (conj {:arglists (list 'quote (sigs fdecl))} m)
          m (let [inline (:inline m)
                  ifn (first inline)
                  iname (second inline)]
              ;; same as: (if (and (= 'fn ifn) (not (symbol? iname))) ...)
              (if (if (clojure.lang.Util/equiv 'fn ifn)
                    (if (instance? clojure.lang.Symbol iname) false true))
                ;; inserts the same fn name to the inline fn if it does not have
                ;; one
                (assoc m
                  :inline (cons ifn
                                (cons (clojure.lang.Symbol/intern
                                        (.concat (.getName ^clojure.lang.Symbol
                                                           name)
                                                 "__inliner"))
                                      (next inline))))
                m))
          m (conj (if (meta name) (meta name) {}) m)]
      (list 'def
            (with-meta name m)
            ;;todo - restore propagation of fn name
            ;;must figure out how to convey primitive hints to self calls first
            ;;(cons `fn fdecl)
            (with-meta (cons `fn fdecl) {:rettag (:tag m)})))))
nil
zprint.core=> (czprint-fn defn {:style :justified})
(def
  ^{:doc
      "Same as (def name (fn [params* ] exprs*)) or (def
    name (fn ([params* ] exprs*)+)) with any doc-string or attrs added
    to the var metadata. prepost-map defines a map with optional keys
    :pre and :post that contain collections of pre or post conditions.

  Spec:
    args: (cat :fn-name simple-symbol?
               :docstring (? string?)
               :meta (? map?)
               :fn-tail
                 (alt :arity-1 :clojure.core.specs.alpha/params+body
                      :arity-n
                        (cat :bodies
                               (+ (spec :clojure.core.specs.alpha/params+body))
                             :attr-map (? map?))))
    ret: any?",
    :arglists '([name doc-string? attr-map? [params*] prepost-map? body]
                [name doc-string? attr-map? ([params*] prepost-map? body) +
                 attr-map?]),
    :added "1.0"}
  defn
  (fn defn [&form &env name & fdecl]
    ;; Note: Cannot delegate this check to def because of the call to (with-meta
    ;; name ..)
    (if (instance? clojure.lang.Symbol name)
      nil
      (throw (IllegalArgumentException.
               "First argument to defn must be a symbol")))
    (let [m     (if (string? (first fdecl)) {:doc (first fdecl)} {})
          fdecl (if (string? (first fdecl)) (next fdecl) fdecl)
          m     (if (map? (first fdecl)) (conj m (first fdecl)) m)
          fdecl (if (map? (first fdecl)) (next fdecl) fdecl)
          fdecl (if (vector? (first fdecl)) (list fdecl) fdecl)
          m     (if (map? (last fdecl)) (conj m (last fdecl)) m)
          fdecl (if (map? (last fdecl)) (butlast fdecl) fdecl)
          m     (conj {:arglists (list 'quote (sigs fdecl))} m)
          m     (let [inline (:inline m)
                      ifn    (first inline)
                      iname  (second inline)]
                  ;; same as: (if (and (= 'fn ifn) (not (symbol? iname))) ...)
                  (if (if (clojure.lang.Util/equiv 'fn ifn)
                        (if (instance? clojure.lang.Symbol iname) false true))
                    ;; inserts the same fn name to the inline fn if it does not
                    ;; have one
                    (assoc m
                      :inline (cons
                                ifn
                                (cons (clojure.lang.Symbol/intern
                                        (.concat (.getName ^clojure.lang.Symbol
                                                           name)
                                                 "__inliner"))
                                      (next inline))))
                    m))
          m     (conj (if (meta name) (meta name) {}) m)]
      (list 'def
            (with-meta name m)
            ;;todo - restore propagation of fn name
            ;;must figure out how to convey primitive hints to self calls first
            ;;(cons `fn fdecl)
            (with-meta (cons `fn fdecl) {:rettag (:tag m)})))))
nil
```
In addition, you might note the addition of the specs for `defn` added to the docstring. Which has nothing to do with your issue, but is a nice feature nevertheless.

If by "utilize elastic tabstops", you mean "make it look like the vertical alignment example in the first link", then the answer is most certainly "yes"!

**Comment by dijonkitchen** [comment]
That's awesome! Since it can do it, a user somehow run it on saving a file so code can be neatly formatted as you edit it?

**Comment by kkinnear** [comment]
There are about three ways that you can use zprint when editing:

1. You can use the [zprint-filter](https://github.com/kkinnear/zprint/blob/master/doc/graalvm.md) (a program which accepts Clojure(script) source on stdin and outputs formatted Clojure(script) source on stdout.  Most editors allow you to pipe a section of text through an external program.  Certainly vi and emacs and sublime do.  This is what I do while editing, as having it formatted correctly while I'm creating or modifying a function is a big help to me.  So, mostly, I keep my files formatted while I'm working on them.  If the graalvm stuff isn't to your liking, there is also a slightly slower but still pretty fast way to get a [zprint-filter](https://github.com/kkinnear/zprint/blob/master/doc/filter.md) working.
2. You can trigger the zprint-filter when you save a file to do the formatting whenever you save the file.  Not every editor can be configured to do this, but many can.  Exactly how you would do that is pretty much up to you to figure out for your editor.  I know some people are using zprint to do this, but it isn't my personal approach.
3. You can format your file at the command line, using l[ein-zprint](https://github.com/kkinnear/lein-zprint) or other tool like that.  I do this before I push my code to github, but otherwise I mostly just do #1.

**Comment by dijonkitchen** [comment]
Thanks @kkinnear I'll close this issue for future reference to those interested!
