### ISSUE TITLE
Ignoring formatting in (comment) forms

### ISSUE THREAD

**Issue by danieroux** [kkinnear/zprint#71]
The formatting (especially spacing between top level forms) have meaning to me in a (comment) form. zprint right now smushes all the forms together.

Rest of the file I don't care. I would like to keep this manual formatting:

```clojure
(comment 

  (def burst-segment {:body " 0,PT2,17.61,18.3000"})

  (make-sensordata-from-burst-csv burst-segment)
  (make-sensordata-from-burst-string (make-sensordata-from-burst-csv burst-segment))

  (start-csv-dump-of-burst!)
  (start-csv-dump-of-interval!)

  ;; fin
)
```

**Comment by danieroux** [comment]
I can add `;!zprint {:format :off}` to every comment form, and I would like to be able to globally do it

**Comment by kkinnear** [comment]
Thanks for the clear explanation.  I understand what you want and why you want it.  I will work on making that possible.  I have an idea of how it might work out, but I need to do a little research to see how well that idea will go together.  But it seems like a good idea, and if people can turn off formatting for `comment`, they could turn off formatting for other things too, and that would probably be useful well beyond your particular use case -- which is always a nice plus.

**Comment by kkinnear** [comment]
I've been thinking about how to do this.  Some of the ideas:
1. simply not format anything in `comment` forms.  
2. respect newlines at all levels in `comment` forms, but otherwise format things correctly (which would mean indenting them correctly, but not shifting lines)
3. respect newlines at the top level of comment forms, but do regular formatting of anything below the first level

Do any of these sound better or worse to you?  I'm not sure which ones would work out in a reasonable way.  I'm leaning toward trying to do 2, and then see if it is straightforward to add on 3.  But I'm interested in your opinion, since this was your idea.  Thanks.

**Comment by danieroux** [comment]
2 is interesting to me. And 2 in other places will be interesting to me too.

Sometimes I do like to create space around forms in a defn, for example, to "punctuate" the flow of thoughts.

(it's usually an indication that the defn is too long, but not always)

**Comment by kkinnear** [comment]
You can now get exactly what you want in version 0.5.0.  See the section: "Altering the formatting inside of certain functions" in the README, and in that section you will see an example which will do precisely what you want -- keep newlines at the top level of a `comment` function, but format everything down one level from that normally.
