### ISSUE TITLE
Native-image version changes international characteres to `??`

### ISSUE THREAD

**Issue by mynomoto** [kkinnear/zprint#78]
`é`, `á`, `ã`, `ç` are all transformed to `??` using the filter version.

Tried the zprintl-0.4.13 version on the releases page, on both arch linux and ubuntu. Both from vim and using `zprintl-0.4.13 < file.clj > file.clj.new`.

Maybe I'm doing something wrong?

**Comment by mynomoto** [comment]
The filter version using `zprint-filter-0.4.13` works fine, sorry about the unclear report.

**Comment by kkinnear** [comment]
I did some investigating, and from what I've been able to figure out, graalvm builds a native image for one locale/char-set.  Since I build `zprintl-0.4.13`, that would be my locale/char-set, obviously not yours.  It is possible that might change in some future release of graalvm.

For now, I think that the two answers for you (and anyone with the same problem) are:

1. Use the appcds script and the zprint-filter to use appcds to launch the regular JVM version, which is pretty fast.
2. Use the zprint-filter and get a copy of graalvm yourself, and build the lightning fast version on your machine, which should support your locale/char-set by default.

Option 2 isn't hard, really.  You have to download [graalvm](https://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html). This link is for RC9, and I have only used RC8 so far, but I would expect it to work.  Then you have to build it.  The actual building is pretty simple.  Here is a file that should work:
```
#!/bin/bash
# First argument -- location of graalvm
# Second argument -- version of zprint-filter
export PATH=$1/bin:$PATH
export JAVA_HOME=$1
echo "$PATH"
pwd
whereis native-image
native-image --version
native-image --no-server -J-Xmx4G -J-Xms2G -jar zprint-filter-$2 -H:Name="zprintl-$2" -H:+ReportUnsupportedElementsAtRuntime
```
I don't use exactly that file (or run native on Linux), but I think that will do it for you.  If not, it is close.
Once you get the file to start working, you only have to wait.  And wait.  And wait.  It takes several minutes (like maybe 5 or more) for graalvm to build the native image.  But it is worth the one-time wait.

I hope this helps!

**Comment by mynomoto** [comment]
Yeah, that works, a coworker did build it and we are gladly using it, way better/faster that the way we were using before. I think the issue is that the build are not being made on a UTF-8 charset more than other locale related issues, would a PR that changes that be welcome?

**Comment by kkinnear** [comment]
Yes, I'd love a PR which would change that!  Thanks!
