### ISSUE TITLE
Use regex or a subset of to match functions

### ISSUE THREAD

**Issue by mynomoto** [kkinnear/zprint#8]
So we could use a config map like
```clojure
{:fn-map {"def*" :arg1-body}}
```
or
```clojure
{:fn-map {#"def*" :arg1-body}}
```
and it would apply for `def`, `defn`, `defproject` and so on. Ideally the regex would only be used if no direct matches were found so if we add a entry for `defmethod` it would be used instead of `#"def*"`.
It would simplify the config for common cases like `def*`, `with-*`, `*->>`.

**Comment by kkinnear** [comment]
This is an interesting idea.  If there were no performance penalty, I could see it making sense.  But I think that I'd have to try every regex in the map (or vector or whatever) on every function.  Kind of like ordered rules.  I would think that would have to have some performance impact.

Now, I could see some optimizations, like just allowing a trailing * and not using a real regex, and then I could store them indexed by the first two letters or something and that would reduce the need to match on lots of "rules".   I don't know if this would have a performance impact or not, actually.  Would probably need to implement it to find out. 

It does seem like a lot of mechanism in order to make configuring the functions a bit simpler.  If it were either simple to do and had no performance impact, or configuring function types was hard, then this would make a lot of sense to me.  But I don't, quite, see either of those being true.  But perhaps I'm missing something and haven't understood your suggestion correctly.

**Comment by mynomoto** [comment]
The way I see you understood what I meant. In the clojure community there are lots of patterns that more or less followed. So in my experience having a way to configure patterns instead of specific things is helpful. Almost always I want things that follows the pattern `def*` to be formatted in the same way. This avoids having to add configuration each time I add on lib that follows that kind of pattern. The gain depends on the libraries you use but I don't have exceptions on that rule on my vim config that accepts `def*` as a indentation pattern. I have only a couple of those in there and they do a pretty good job. But I understand that you may not want to add that, it's up to you.

**Comment by kkinnear** [comment]
Thanks for the feedback. I do know what you mean about configuring patterns instead of specific functions.  I'm going to think about this one a bit more.  Before I implemented it, I would do some prototyping and performance measurements, but that wouldn't be difficult.  I'll leave this as a "maybe" for now.

**Comment by riotrah** [comment]
Hi Kkinnear, was going to make a duplicate issue before I found this.

If there was an opt-in way to do this, that would be lovely, depending on how hard the implementation cost would be for you of course.

My use case is that we have a couple of ns's in our codebase that specifically follow a specific pattern for their public fns/macros, such that they share a common formatting pattern. If it helps any, they must all be some slight variation of `:gt2-force-nl`. 

This ns may grow or change and its fn-map is already quite large to the extent of adding much noise to the config (in my opinion I suppose).

Again this isn't the biggest deal, but being able to use regexes, wildcard(s), or otherwise configure such hyper-specific namespaces "in one go" would be great! Thanks.

PS: a public example might be `lilactown`'s `helix.dom`, whose docs suggest usage like:

```clojure
(ns ... [helix.dom :as d] ... )

(defnc ... 
	(d/div ... ))
```

That's similar to my use cases, and is in fact one of them.

Thanks again as always for such an awesome project. Hope necro'ing this old thread wasn't inconvenient for you.

**Comment by kkinnear** [comment]
I have explored a way to do regex kinds of things with what I think is the currently released code.  I need to try it out for sure with `1.2.4` to make sure it will work, but I'll do that soon.  I'm currently tied up for a week or so, but I'll try to get back to you in the next week or so.

**Comment by kkinnear** [comment]
Well, I have a way to do regex recognition of functions and then to return an options map to format them.  The new thing that you can do with the `:fn-map`, where you 'alias' one function to another will not (yet) work with this approach.  That's part of what I am doing for the next release.  So you can't sort of 'reset' the `:fn-map` in the regex recognizer.  But you can return an options map to format the thing that is recognized, which is quite powerful and flexible.

This whole regex thing only really makes sense when you have some particular formatting and you would like to have it used for a lot of different functions.  If you could give me one example of a function and the formatting you would like to use for it, (or what you would like it to look like, and I will figure out the formatting), I will try it out and ensure that it will work in the regex recognizer, and give you a framework (or kind of a worked example) which you can extend with as many regexes as you want, using the existing `1.2.4` code already released.

I would be interested in your reaction to the approach to regex processing I have developed, so this would also be valuable to me.

To be clear, I'm hoping that you will give me a function and either the zprint config that gives you the formatting you want, or a function and what you would like it to look like (and I'll figure out the formatting).  From that I can try it out and give you back a framework into which you can place one or more regexes to do what you want.

**Comment by kkinnear** [comment]
1.2.5 has regex processing for function names.  See the CHANGELOG.md entry for 1.2.5 for details and where to find examples of how to do this.
