### ISSUE TITLE
Disable fitting behavior altogether?

### ISSUE THREAD

**Issue by vemv** [kkinnear/zprint#90]
Hey there,

still exploring what zprint is capable of.

I think I found a behavior which is constantly getting in my way.

Given this minimal ~/.zprintrc:

```
{:old? false
 :width 4000}
```

Formatting any given file will turn it unreadable, because of the fitting behavior described here: https://github.com/kkinnear/zprint/tree/acccfc090a702636aa78dd0612e942c2149db730#controlling-single-and-multi-line-output

Of course I don't use a width of 4000. But for any value, I'll face unexpected formatting because of the following difference in approaches:

* for zprint a width works a _permission_ to place more things into the same line
* for me, a width is a _limit_ which formatting rules may not surpass. Otherwise it does not guide where to place code: that is the job of each formatting rule.

IOW, there should be one way of formatting `do` (example: newline after `do`, two-space indentation), and only one. With the sole marginal exception of hitting the width, where zprint could get more creative.

I did try playing with `:fn-force-nl`, `:fn-gt2-force-nl`, `:fn-gt3-force-nl` but it didn't seem to have effect.

What do you think?

Thanks - Victor

**Comment by kkinnear** [comment]
You have expressed what zprint does well -- the width is a _permission_.  zprint tries to get as much to fit within the allowable width in order to reduce the cognitive load when looking at code.  As part of that process, zprint will perform several checks when attempting to format something:
1. If the expression will fit on one line and there is no directive to disallow one line output, it formats it on one line.  If that doesn't work, then...
2. If the first two elements of the expression will fit on one line, zprint will try to format it that way and labels it a **hang**.
3. zprint will format the initial element on the line and place the next elements indented on successive lines underneath the first one.  zprint labels that a **flow**.

If #1 didn't work, and if both the hang and the flow worked, then zprint will evaluate both the hang and the flow to determine which is _better_.  Better is defined as a complex set of empirical heuristics, trying to format the code (or data structure) in a way that looks similar to how a human would format it.

It sounds to me like that fact that there isn't one way to format every function is part of what is bothering you.  One thing you could try would be to turn off the processing for hangs.  In most of the code I've looked at, hangs do occur but not very frequently.  They show up in formatting examples a lot.  You can turn them off by using the style `{:style :no-hang}`.  This won't affect things that fit on a single line, but it will stop the comparison between hang and flow formatting.  

See how `{:style :no-hang}` works for you, and let me know.  If it doesn't do what you want, 2 or 3 specific examples of what goes in and what you would like to have come out would help me to respond.

**Comment by vemv** [comment]
Hi again,

I have restated the problem in https://github.com/kkinnear/zprint/issues/170 from a different point of view, disregarding the notion of `:width`.

I think this new issue is simpler to discuss with a concrete goal and examples.

(For the record, I have tried the suggestion above, and have always played with zprint over the years. But I've never been quite sure if I understood its API, philosophy etc. Maybe I tend to try to use it with different/incompatible goals)
