### ISSUE TITLE
Is native zprint doesn't support `.zprintrc`?

### ISSUE THREAD

**Issue by netpyoung** [kkinnear/zprint#93]
```
[~/test]$ cat test.clj
(ns helloworld
  (:require [x.configs :as configs]
    [a]))
[~/test]$ cat .zprintrc
{:style [:community :how-to-ns]}

[~/test]$ zprint < test.clj
(ns helloworld
  (:require [x.configs :as configs]
            [a]))

[~/test]$ zprint '{:style [:community :how-to-ns]}' < test.clj
(ns helloworld
  (:require
   [x.configs :as configs]
   [a]))
```
It seems like doesn't using `.zprintrc` on native-image

**Comment by kkinnear** [comment]
I can't reproduce this problem.  Here is what I get using the Mac graalvm zprint:
```clojure
$ more i93.clj
(ns helloworld
  (:require [x.configs :as configs]
    [a]))
$ more ~/.zprintrc
{:style [:community :how-to-ns]}
$ ./zprintm-0.4.15 <i93.clj
(ns helloworld
  (:require
   [x.configs :as configs]
   [a]))
$ vi ~/.zprintrc
$ more ~/.zprintrc
{}
$ ./zprintm-0.4.15 <i93.clj
(ns helloworld
  (:require [x.configs :as configs]
            [a]))
$ 
```
So, to debug this I need to gather more information.  Some questions:

1. What platform (that is, operating system and version) are you operating on?
2. What version of zprint are you using?
3. What is the value of `HOME` in your environment?
4. What version of Java are you using?

I would not be surprised if the issue were #3, since zprint looks for `HOME` in the environment, and then looks for the file `HOME/.zprintrc`.  That isn't quite true -- it actually doesn't use `/` but uses the Java `file-separator`.   

But the answers to my questions should get us closer to what is going on.

Thanks!

**Comment by netpyoung** [comment]
I thought It will be work `~/test/.zprintrc` without `~/.zprintrc`file,.
and finally, I found that caused by missing of `~/.zprintrc` with `:search-config? true`.
could I using zprint without `~/.zprintrc`?



## environment
```
[~/test]$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.2 (18C54)
      Kernel Version: Darwin 18.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: pyoung
      User Name: Kim Eunpyoung (pyoung)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 18:04

[~/test]$ 
[~/test]$ ls -al `which zprint`
lrwxr-xr-x 29 pyoung 22 Jan  8:26 /usr/local/bin/zprint -> /usr/local/bin/zprintm-0.4.14
[~/test]$ 
[~/test]$ echo $HOME
/Users/pyoung
[~/test]$ 
[~/test]$ java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-20181024123616.buildslave.jdk8u-src-tar--b12)
GraalVM 1.0.0-rc11 (build 25.192-b12-jvmci-0.53, mixed mode)
```

**Comment by kkinnear** [comment]
Thanks, I think you have figured out the problem.  zprint will not look at `.zprintrc` files in any directory other than your home directory unless the `.zprintrc` in your home directory includes `:search-config? true`.  Once you put `{:search-config? true}` in your home directory, you don't ever need to mess with it again.  zprint will always search for you.

To answer your question, you can of course use zprint without having a `~/.zprintrc` file, but it won't look for any other `.zprintrc` files in that case.  

You could create an alias for zprint which included the configuration that you want, since you can pass `zprintm-0.4.14` (or whatever) an options map:
```
$zprint '{:style [:community :how-to-ns]}' <core.clj >whatever.clj
```
If you made an alias that included the options map, you could still type `zprint` and it would work.

One enhancement that I would be willing to implement would be to look up an environment variable which contained an options map, where you could set `{:search-config? true}` in that environment variable.  I don't know if that would be better for you or not -- you would still have to do something, but it would be an environment variable and not a file.

Another alternative is that I'm considering making `:search-config?` default to `true` when I move to release `0.5.0`, which will probably be in a few months.  So, if you could get by with using the existing `~/.zprintrc` solution for now, it would probably be unnecessary in a few months.  I don't know if that would be any help for you.

**Comment by netpyoung** [comment]
Thank you for reply that.
Currently I'm trying apply zprint to our project for fmt.
I hoping default value of `:search-config true`.
