### ISSUE TITLE
Is it intentional that there is no native executable assets on 0.4.15 release?

### ISSUE THREAD

**Issue by mynomoto** [kkinnear/zprint#95]

**Comment by kkinnear** [comment]
No, it wasn't.  Thanks for letting me know.  I did a hurried re-release because I had missed a warning given by the latest Clojurescript compiler that I had to fix, and I did all of the things for a release but got interrupted before I finished the job of uploading the files to GitHub and obviously never got back to it.  Thanks again for letting me know!  Should be all there now.

**Comment by mynomoto** [comment]
Thanks!
